/**
 * WP5 · Gallery page (spec §2.12, §7.3): JS-free contact sheet, generated by
 * scripts/build-gallery.mjs from gallery/assets/data/images.json.
 */
import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { nights, photoNames } from "../js/lib/derive.js";

const IMAGES = JSON.parse(readFileSync(new URL("../gallery/assets/data/images.json", import.meta.url), "utf8"));
const NIGHTS = nights(photoNames(IMAGES)).length;

test("gallery works without JavaScript: all links, night groups, no scripts", async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false });
  const page = await context.newPage();
  const requests = [];
  page.on("request", (r) => requests.push(r.url()));
  await page.goto("/gallery/");
  await expect(page.getByRole("heading", { level: 1, name: "Abseits der Tabs." })).toBeVisible();
  const links = page.locator(".photo-grid a");
  await expect(links).toHaveCount(IMAGES.length);
  expect(IMAGES.length).toBe(77);
  await expect(links.first()).toHaveAttribute("href", "assets/img/large/IMG_20200924_233029.jpg");
  const hrefs = await links.evaluateAll((els) => els.map((a) => a.getAttribute("href")));
  expect(hrefs).toEqual(IMAGES.map((i) => `assets/img/large/${i.name}.jpg`));
  await expect(page.locator("main h2")).toHaveCount(NIGHTS);
  await expect(page.locator("main h2").first()).toHaveText(/^Nacht 01 · \p{L}+, \d\d\.\d\d\.\d{4}$/u);
  await expect(page.locator("script")).toHaveCount(0);
  await expect(page.locator("#foto-01")).toHaveAttribute("href", "assets/img/large/IMG_20200924_233029.jpg");
  await expect(page.locator('img[alt="Galerieaufnahme 01"]')).toHaveCount(1);
  const origin = new URL(page.url()).origin;
  expect(requests.filter((u) => new URL(u).origin !== origin)).toEqual([]);
  await context.close();
});

test("gallery reflows at 320 px without horizontal scroll", async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 320, height: 700 } });
  const page = await context.newPage();
  await page.goto("/gallery/");
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await context.close();
});
