// built by scripts/pack-probes.mjs from src/
export const PROBE_IDS=["bomberman-chain","melodai-mixer","theater-saalplan","transcripator-pow","beatguessr-years"];const REGISTRY={"bomberman-chain":{kind:"nachbau",load:()=>Promise.resolve(__bomberman)},"melodai-mixer":{kind:"nachbau",load:()=>Promise.resolve(__mixer)},"theater-saalplan":{kind:"nachbau",load:()=>Promise.resolve(__saalplan)},"transcripator-pow":{kind:"echt",load:()=>import("./werk.js").then((m)=>m.hashsuche)},"beatguessr-years":{kind:"echt",load:()=>import("./werk.js").then((m)=>m.jahresregler)},};const CSS_HREF="css/probes.css";let cssReady=null;function ensureCss(){if(typeof document==="undefined")return Promise.resolve();if(cssReady)return cssReady;const href=new URL(CSS_HREF,document.baseURI).href;const existing=[...document.querySelectorAll('link[rel="stylesheet"]')].find((l)=>l.href===href);cssReady=new Promise((resolve)=>{if(existing?.sheet)return resolve();let retried=false;const add=(url)=>{const link=document.createElement("link");link.rel="stylesheet";link.href=url;document.head.append(link);return link;};const watch=(link)=>{link.addEventListener("load",()=>resolve(),{once:true});link.addEventListener("error",()=>{if(retried)return resolve();retried=true;watch(add(`${CSS_HREF}?r=1`));},{once:true},);};watch(existing??add(CSS_HREF));setTimeout(resolve,1500);});return cssReady;}
export function calmSource(ctx={}){const m=ctx.motion;if(m&&"calm"in m)return m;const mq=typeof matchMedia==="function"?matchMedia("(prefers-reduced-motion: reduce)"):null;return{get calm(){return Boolean(ctx.calm)||Boolean(mq?.matches)||document.documentElement.dataset.motion==="paused";},onCalmChange(){return()=>{};},};}
export function announcer(ctx={}){if(typeof ctx.announce==="function")return ctx.announce;let el=null;return(text)=>{if(!text)return;el??=document.getElementById("announcer-polite");if(!el){el=document.createElement("div");el.id="announcer-polite";el.className="vh";el.setAttribute("aria-live","polite");document.body.append(el);}
el.textContent="";requestAnimationFrame(()=>(el.textContent=text));};}
let uid=0;export const nextId=(prefix)=>`${prefix}-${++uid}`;export async function mountProbe(stage,id,ctx={}){const entry=REGISTRY[id];if(!entry||!stage)throw new Error(`Unbekanntes Probestück: ${id}`);const fallback=[...stage.childNodes];let mod;try{[mod]=await Promise.all([entry.load(),ensureCss()]);}catch(error){showJammed(stage,ctx);throw error;}
if(ctx.signal?.aborted)return{destroy(){},pause(){},resume(){}};const active=typeof document!=="undefined"?document.activeElement:null;const watch=active&&active!==document.body&&!stage.contains(active)&&stage.compareDocumentPosition(active)&4&&inView(active);const shell=document.createElement("div");shell.className="probe-live";stage.replaceChildren(shell);stage.classList.add("is-live");stage.dataset.probeState="live";let inner;try{inner=await mod.mount(shell,{...ctx,id,kind:entry.kind});}catch(error){stage.replaceChildren(...fallback);stage.classList.remove("is-live");delete stage.dataset.probeState;showJammed(stage,ctx);throw error;}
if(ctx.chip&&mod.CHIP){const row=document.createElement("p");row.className="probe-chip-row probe-chip-row--inline";const chip=document.createElement("span");chip.className="chip chip--probe";chip.textContent=entry.kind==="echt"?"Echt":"Nachbau";const text=document.createElement("span");text.className="probe-chip-text";text.textContent=mod.CHIP;row.append(chip," ",text);shell.append(row);const prevDestroy=inner.destroy;inner.destroy=()=>{row.remove();prevDestroy.call(inner);};}
if(watch)requestAnimationFrame(()=>document.activeElement===active&&!inView(active)&&active.scrollIntoView({block:"nearest"}));let destroyed=false;const handle={id,kind:entry.kind,pause:()=>inner.pause?.(),resume:()=>inner.resume?.(),destroy(){if(destroyed)return true;destroyed=true;try{inner.destroy?.();}finally{stage.replaceChildren(...fallback);stage.classList.remove("is-live");delete stage.dataset.probeState;}
return true;},};ctx.signal?.addEventListener("abort",()=>handle.destroy(),{once:true});return handle;}
function inView(el){const r=el.getBoundingClientRect();return r.height>0&&r.top>=0&&r.bottom<=innerHeight;}
function showJammed(stage,ctx){if(stage.querySelector(".probe-jammed"))return;const p=document.createElement("p");p.className="probe-jammed chip chip--note";p.append("Das Probestück klemmt gerade.");if(ctx.originalUrl){p.append(" Das Original geht aber: ");const a=document.createElement("a");a.href=ctx.originalUrl;a.target="_blank";a.rel="noopener noreferrer";a.innerHTML='Ausprobieren <svg class="i" aria-hidden="true" focusable="false"><use href="#i-arrow-ne"></use></svg><span class="vh"> (öffnet neue Seite)</span>';p.append(a);}
stage.querySelector(".chip--note")?.replaceWith(p)??stage.append(p);}
const __saalplan=(()=>{const KIND="nachbau";const LAYOUT=[{row:"A",seats:[2,3,4,5,6,7,8,9]},...["B","C","D","E","F","G"].map((row)=>({row,seats:[1,2,3,4,5,6,7,8,9,10],})),];const AISLE_AFTER=5;const MAX_PICK=5;const SHOW={title:"Romeo und Julia",house:"Kolpingtheater Ramsen",season:"Wintertheater",day:"Mo 28.12.2026",time:"19:30",hint:"Wähle eure freien Plätze. Ihr könnt auch getrennt sitzen. Wenn möglich, vermeide einzelne freie Plätze dazwischen.",};const SEATS=LAYOUT.flatMap(({row,seats},ri)=>seats.map((n)=>({id:`${row}${n}`,row,n,ri,block:n<=AISLE_AFTER?0:1,})),);const SEAT_COUNT=SEATS.length;const CHIP=`Nachbau: der Saalplan von „${SHOW.title}“ mit denselben ${SEAT_COUNT} Plätzen wie in der echten Buchung. Gebucht wird hier nichts, und der QR-Code auf dem Ticket ist nur Deko.`;const BY_ID=new Map(SEATS.map((s)=>[s.id,s]));const seatLabel=(id)=>{const s=BY_ID.get(id);return s?`Reihe ${s.row}, Platz ${s.n}`:"";};function loneGaps(booked,picked){const taken=(id)=>booked.has(id)||picked.has(id);const out=[];for(const{row,seats}of LAYOUT){for(const block of[seats.filter((n)=>n<=AISLE_AFTER),seats.filter((n)=>n>AISLE_AFTER),]){block.forEach((n,i)=>{const id=`${row}${n}`;if(taken(id)||block.length<2)return;const nb=[block[i-1],block[i+1]].filter((x)=>x!==undefined).map((x)=>`${row}${x}`);if(nb.every(taken)&&nb.some((x)=>picked.has(x)))out.push(id);});}}
return out;}
function step(id,key){const s=BY_ID.get(id);if(!s)return SEATS[0].id;const row=LAYOUT[s.ri].seats;const i=row.indexOf(s.n);const inRow=(j)=>`${s.row}${row[Math.max(0,Math.min(row.length-1,j))]}`;const toRow=(ri)=>{const r=LAYOUT[Math.max(0,Math.min(LAYOUT.length-1,ri))];const n=r.seats.reduce((best,x)=>(Math.abs(x-s.n)<Math.abs(best-s.n)?x:best),r.seats[0],);return`${r.row}${n}`;};switch(key){case"ArrowLeft":return inRow(i-1);case"ArrowRight":return inRow(i+1);case"ArrowUp":return toRow(s.ri-1);case"ArrowDown":return toRow(s.ri+1);case"Home":return inRow(0);case"End":return inRow(row.length-1);case"PageUp":return toRow(0);case"PageDown":return toRow(LAYOUT.length-1);default:return id;}}
function seatList(ids){const rows=new Map();for(const s of SEATS)
if(ids.has(s.id))rows.set(s.row,[...(rows.get(s.row)??[]),s.n]);return[...rows].map(([row,ns])=>`${row} ${ns.join(", ")}`).join(" · ");}
function prng(seed){let a=seed>>>0;return()=>{a=(a+0x6d2b79f5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
const hashStr=(str)=>[...str].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619),2166136261,);function decoPattern(seed,size=21){const rnd=prng(hashStr(String(seed)));const m=Array.from({length:size},()=>new Array(size).fill(0));const reserved=Array.from({length:size},()=>new Array(size).fill(false),);const finder=(ox,oy)=>{for(let y=-1;y<=7;y++)
for(let x=-1;x<=7;x++){const X=ox+x;const Y=oy+y;if(X<0||Y<0||X>=size||Y>=size)continue;reserved[Y][X]=true;const ring=Math.max(Math.abs(x-3),Math.abs(y-3));m[Y][X]=x>=0&&x<=6&&y>=0&&y<=6&&ring!==2?1:0;}};finder(0,0);finder(size-7,0);finder(0,size-7);for(let i=8;i<size-8;i++){m[6][i]=m[i][6]=i%2===0?1:0;reserved[6][i]=reserved[i][6]=true;}
for(let y=0;y<size;y++)
for(let x=0;x<size;x++)
if(!reserved[y][x])m[y][x]=rnd()<0.48?1:0;return m;}
const patternPath=(m)=>{let d="";m.forEach((row,y)=>row.forEach((on,x)=>on&&(d+=`M${x} ${y}h1v1h-1z`)),);return d;};function mount(root,ctx={}){const motion=calmSource(ctx);const say=announcer(ctx);const ids={how:nextId("ps-how"),map:nextId("ps-map"),hint:nextId("ps-hint"),};const booked=new Set();let picked=new Set();let cursor="D5";let printed=0;const timers=new Set();const later=(fn,ms)=>{const t=setTimeout(()=>{timers.delete(t);fn();},ms);timers.add(t);};root.classList.add("probe","probe-saal");root.tabIndex=-1;const col=(n)=>(n<=AISLE_AFTER?n+1:n+2);const seatsHtml=LAYOUT.map(({row,seats},ri)=>`<span class="ps-rowlab" data-rowlab="${row}" style="grid-row:${ri+1}" aria-hidden="true">${row}</span>`+seats.map((n)=>`<button type="button" class="ps-seat" data-seat="${row}${n}" style="grid-row:${ri+1};grid-column:${col(n)}" aria-label="Reihe ${row}, Platz ${n}" aria-pressed="false" tabindex="-1"><span aria-hidden="true">${n}</span></button>`,).join(""),).join("");root.innerHTML=`
<div class="ps-house">
<header class="ps-hud meta">
<span class="ps-hud-tag">Saalplan · Nachbau</span>
<span class="ps-hud-show"><b>${SHOW.title}</b> · ${SHOW.day} · ${SHOW.time}</span>
</header>
<div class="ps-stage" aria-hidden="true">
<svg class="ps-arc" viewBox="0 0 600 60" preserveAspectRatio="none" focusable="false"><path d="M8 52 Q300 -12 592 52"/></svg>
<span class="ps-stage-label">Bühne</span>
</div>
<div class="ps-map" id="${ids.map}" role="group" aria-roledescription="Saalplan" aria-label="Saalplan „${SHOW.title}“, ${SEAT_COUNT} Plätze in ${LAYOUT.length} Reihen, Bühne vorne" aria-describedby="${ids.how}">
${seatsHtml}
<span class="ps-aisle" style="grid-row:1 / span ${LAYOUT.length}" aria-hidden="true"></span>
</div>
<ul class="ps-legend meta" aria-label="Legende">
<li><i class="ps-dot" aria-hidden="true"></i>Frei</li>
<li><i class="ps-dot ps-dot--pick" aria-hidden="true"></i>Deine Auswahl</li>
<li><i class="ps-dot ps-dot--taken" aria-hidden="true"></i>Belegt</li>
</ul>
<p class="ps-hint" id="${ids.hint}"><span class="ps-hint-q">„${SHOW.hint}“</span> <span class="ps-hint-src meta">Hinweis aus der echten Buchung</span></p>
<p class="ps-warn" data-ps="warn" hidden></p>
</div>
<div class="probe-toolbar">
<button class="button probe-btn" type="button" data-ps="print" disabled>Ticket drucken</button>
<button class="button button--ghost probe-btn" type="button" data-ps="clear" disabled>Auswahl leeren</button>
<button class="button button--ghost probe-btn" type="button" data-ps="reset" hidden>Saal leeren</button>
<p class="probe-readout meta" data-ps="readout"><span><b data-ps="count">0</b> von ${MAX_PICK} Plätzen</span><span><b data-ps="free">${SEAT_COUNT}</b> von ${SEAT_COUNT} frei</span></p>
</div>
<div class="ps-slot" data-ps="slot"><p class="ps-slot-empty meta" data-ps="slotnote">Hier kommt dein Ticket raus.</p></div>
<p class="probe-howto" id="${ids.how}">Platz antippen oder mit Pfeiltasten wählen · Enter oder Leertaste: auswählen · Pos1/Ende: Reihenanfang/-ende · Esc: raus</p>`;const q=(sel)=>root.querySelector(sel);const el={map:q(".ps-map"),seats:new Map([...root.querySelectorAll(".ps-seat")].map((b)=>[b.dataset.seat,b]),),rowlabs:new Map([...root.querySelectorAll(".ps-rowlab")].map((r)=>[r.dataset.rowlab,r,]),),warn:q('[data-ps="warn"]'),print:q('[data-ps="print"]'),clear:q('[data-ps="clear"]'),reset:q('[data-ps="reset"]'),count:q('[data-ps="count"]'),free:q('[data-ps="free"]'),slot:q('[data-ps="slot"]'),house:q(".ps-house"),};el.seats.get(cursor).tabIndex=0;const anim=(node,frames,opts)=>motion.calm||!node.animate?null:node.animate(frames,opts);const shake=(b)=>anim(b,[{transform:"translateX(-3px)"},{transform:"translateX(3px)"},{transform:"none"}],{duration:180,easing:"steps(3, end)"});function spotlight(id){const b=el.seats.get(id);if(!b)return;const m=el.house.getBoundingClientRect();const r=b.getBoundingClientRect();if(!m.width)return;el.house.style.setProperty("--mx",`${(((r.left+r.width/2-m.left)/m.width)*100).toFixed(1)}%`,);el.house.style.setProperty("--my",`${(((r.top+r.height/2-m.top)/m.height)*100).toFixed(1)}%`,);}
function render(){for(const[id,b]of el.seats){const isPick=picked.has(id);const isTaken=booked.has(id);b.setAttribute("aria-pressed",String(isPick));b.classList.toggle("is-pick",isPick);b.classList.toggle("is-taken",isTaken);if(isTaken){b.setAttribute("aria-disabled","true");b.setAttribute("aria-label",`${seatLabel(id)}, belegt`);}else{b.removeAttribute("aria-disabled");b.setAttribute("aria-label",seatLabel(id));}}
for(const[row,lab]of el.rowlabs)
lab.classList.toggle("is-hot",[...picked].some((id)=>BY_ID.get(id).row===row),);const gaps=loneGaps(booked,picked);for(const[id,b]of el.seats)
b.classList.toggle("is-lone",gaps.includes(id));if(gaps.length){el.warn.hidden=false;el.warn.textContent=`${gaps.length===1?`Platz ${gaps[0]} bliebe`:`Die Plätze ${gaps.join(", ")} blieben`} allein frei. Geht trotzdem, ist nur nicht so schön.`;}else el.warn.hidden=true;const free=SEAT_COUNT-booked.size-picked.size;el.count.textContent=String(picked.size);el.free.textContent=String(free);el.print.disabled=picked.size===0;el.clear.disabled=picked.size===0;el.reset.hidden=booked.size===0;root.dataset.full=String(picked.size>=MAX_PICK);root.dataset.soldout=String(booked.size===SEAT_COUNT);return gaps;}
function focusSeat(id,{move=true}={}){const prev=el.seats.get(cursor);if(prev)prev.tabIndex=-1;cursor=id;const b=el.seats.get(id);b.tabIndex=0;if(move)b.focus({preventScroll:false});spotlight(id);}
function toggle(id){const b=el.seats.get(id);if(booked.has(id)){shake(b);say(`${seatLabel(id)} ist schon belegt.`);return;}
if(picked.has(id)){picked.delete(id);render();say(`${seatLabel(id)} wieder frei. ${picked.size} von ${MAX_PICK}.`);return;}
if(picked.size>=MAX_PICK){shake(b);say(`Mehr als ${MAX_PICK} Plätze gehen nicht auf einmal.`);return;}
picked.add(id);const gaps=render();anim(b,[{transform:"scale(0.82)"},{transform:"scale(1.12)",offset:0.35},{transform:"none"},],{duration:260,easing:"cubic-bezier(.34,1.56,.64,1)"},);anim(b,[{boxShadow:"0 0 0 6px rgb(255 179 71 / 0.55), 0 0 26px 6px rgb(242 96 12 / 0.75)",},{boxShadow:"0 0 0 0 rgb(255 179 71 / 0), 0 0 0 0 rgb(242 96 12 / 0)",},],{duration:1600,easing:"cubic-bezier(.16,1,.3,1)",},);const tail=gaps.length?` Achtung: ${gaps.map(seatLabel).join(" und ")} ${gaps.length===1?"bliebe":"blieben"} allein frei.`:"";say(`${seatLabel(id)} gewählt. ${picked.size} von ${MAX_PICK}.${tail}`);}
function ticket(seats){printed++;const list=seatList(seats);const code=decoPattern(`${SHOW.title}|${SHOW.day}|${list}|${printed}`);const n=seats.size;const stub=document.createElement("article");stub.className="ps-stub";stub.setAttribute("aria-label",`Ticket, Nachbau: ${SHOW.title}, ${SHOW.day}, ${SHOW.time}, ${n===1?"Platz":"Plätze"} ${list}`,);stub.innerHTML=`
<div class="ps-stub-main">
<p class="ps-stub-house meta">${SHOW.house} · ${SHOW.season}</p>
<p class="ps-stub-title">${SHOW.title}</p>
<dl class="ps-stub-facts">
<div><dt>Vorstellung</dt><dd>${SHOW.day}</dd></div>
<div><dt>Beginn</dt><dd>${SHOW.time}</dd></div>
<div><dt>${n===1?"Platz":`${n} Plätze`}</dt><dd>${list}</dd></div>
<div><dt>Eintritt</dt><dd>frei</dd></div>
</dl>
</div>
<div class="ps-stub-code">
<svg class="ps-qr" viewBox="-2 -2 25 25" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><rect x="-2" y="-2" width="25" height="25" class="ps-qr-bg"/><path d="${patternPath(code)}"/></svg>
<p class="ps-stub-note meta">Nur Deko im QR-Look.<br />Scannen bringt nix.</p>
</div>
<span class="ps-stamp" aria-hidden="true">Nachbau</span>`;el.slot.replaceChildren(stub);const a1=anim(stub,[{transform:"translateY(-38%)",clipPath:"inset(0 0 100% 0)"},{transform:"none",clipPath:"inset(0 0 0 0)"},],{duration:640,easing:"cubic-bezier(.16,1,.3,1)",},);anim(stub.querySelector(".ps-qr path"),[{clipPath:"inset(0 0 100% 0)"},{clipPath:"inset(0 0 0 0)"}],{duration:420,delay:260,easing:"steps(21, end)",fill:"backwards",},);const stamp=stub.querySelector(".ps-stamp");anim(stamp,[{opacity:0,transform:"rotate(-14deg) scale(2.1)"},{opacity:1,transform:"rotate(-8deg) scale(0.94)",offset:0.7},{opacity:1,transform:"rotate(-8deg) scale(1)"},],{duration:360,delay:700,easing:"cubic-bezier(.7,0,.84,0)",fill:"backwards",},);if(a1)later(()=>stub.classList.add("is-cool"),1100);else stub.classList.add("is-cool");}
const hadFocus=(btn)=>document.activeElement===btn;function print(){if(!picked.size)return;const seats=new Set(picked);const keep=hadFocus(el.print);for(const id of seats)booked.add(id);picked=new Set();ticket(seats);if(keep){const stub=el.slot.querySelector(".ps-stub");stub.tabIndex=-1;stub.focus({preventScroll:true});stub.scrollIntoView?.({block:"nearest"});}
render();const soldOut=booked.size===SEAT_COUNT;say(`Ticket gedruckt: ${seats.size===1?"Platz":"Plätze"} ${seatList(seats)}. Nachbau, nichts gebucht.${soldOut?" Ausverkauft. Zumindest hier.":""}`,);if(soldOut){const note=document.createElement("p");note.className="ps-soldout";note.textContent="Ausverkauft. Zumindest hier.";el.slot.append(note);}}
function clearPicks(){if(!picked.size)return;const keep=hadFocus(el.clear);const last=[...picked].pop();picked=new Set();if(keep)focusSeat(last??cursor);render();say("Auswahl geleert.");}
function resetHouse(){booked.clear();picked=new Set();focusSeat(cursor);render();el.slot.replaceChildren(Object.assign(document.createElement("p"),{className:"ps-slot-empty meta",textContent:"Hier kommt dein Ticket raus.",}),);say(`Saal wieder leer: ${SEAT_COUNT} Plätze frei.`);}
const onClick=(e)=>{const seat=e.target.closest?.(".ps-seat");if(seat&&root.contains(seat)){focusSeat(seat.dataset.seat,{move:document.activeElement!==seat});toggle(seat.dataset.seat);return;}
const btn=e.target.closest?.("[data-ps]");if(!btn)return;if(btn===el.print)print();else if(btn===el.clear)clearPicks();else if(btn===el.reset)resetHouse();};const onKey=(e)=>{const seat=e.target.closest?.(".ps-seat");if(e.key==="Escape"){if(root.contains(document.activeElement)&&document.activeElement!==root){e.preventDefault();root.focus({preventScroll:true});}
return;}
if(!seat||!/^(Arrow|Home$|End$|Page)/.test(e.key))return;e.preventDefault();const next=step(seat.dataset.seat,e.key);if(next!==seat.dataset.seat)focusSeat(next);};const onOver=(e)=>{const seat=e.target.closest?.(".ps-seat");if(seat)spotlight(seat.dataset.seat);};const onFocusIn=(e)=>{const seat=e.target.closest?.(".ps-seat");if(seat){if(seat.dataset.seat!==cursor)
focusSeat(seat.dataset.seat,{move:false});else spotlight(cursor);}};root.addEventListener("click",onClick);root.addEventListener("keydown",onKey);root.addEventListener("focusin",onFocusIn);el.map.addEventListener("pointerover",onOver);const offCalm=motion.onCalmChange?.(()=>root.getAnimations?.({subtree:true}).forEach((a)=>a.finish()),)??(()=>{});render();const raf=typeof requestAnimationFrame==="function"?requestAnimationFrame(()=>spotlight(cursor)):0;return{pause(){root.dataset.paused="true";},resume(){delete root.dataset.paused;},destroy(){if(raf)cancelAnimationFrame(raf);for(const t of timers)clearTimeout(t);timers.clear();root.removeEventListener("click",onClick);root.removeEventListener("keydown",onKey);root.removeEventListener("focusin",onFocusIn);el.map.removeEventListener("pointerover",onOver);offCalm();for(const a of root.getAnimations?.({subtree:true})??[])a.cancel();root.replaceChildren();root.classList.remove("probe","probe-saal");delete root.dataset.full;delete root.dataset.soldout;delete root.dataset.paused;},};}
return{get KIND(){return KIND},get CHIP(){return CHIP},get mount(){return mount}}})();
const __bomberman=(()=>{const KIND="nachbau";const CHIP="Nachbau: ein vereinfachtes Feld für diese Seite. Die Regel stimmt: Trifft eine Explosion eine Bombe, geht die im selben Tick hoch.";const COLS=15;const ROWS=13;const FLOOR=0;const SOLID=1;const BRICK=2;const FUSE_MS=1400;const FLAME_MS=380;const RANGE=2;const MAX_BOMBS=12;const TICK_MS=1000/60;const idx=(x,y)=>y*COLS+x;const xy=(cell)=>[cell%COLS,Math.floor(cell/COLS)];const DIRS=[[1,0],[-1,0],[0,1],[0,-1],];function mulberry32(seed){let a=seed>>>0;return()=>{a=(a+0x6d2b79f5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function makeGrid(seed=195,density=0.48){const rand=mulberry32(seed);const grid=new Uint8Array(COLS*ROWS);for(let y=0;y<ROWS;y++){for(let x=0;x<COLS;x++){const i=idx(x,y);if(x===0||y===0||x===COLS-1||y===ROWS-1||(x%2===0&&y%2===0))grid[i]=SOLID;else if(Math.abs(x-7)<=2&&Math.abs(y-6)<=1)grid[i]=FLOOR;else grid[i]=rand()<density?BRICK:FLOOR;}}
return grid;}
function makeState(seed){return{grid:makeGrid(seed),bombs:new Map(),flames:new Map()};}
function placeBomb(state,cell,now,{fuse=FUSE_MS,range=RANGE}={}){if(cell<0||cell>=COLS*ROWS)return null;if(state.grid[cell]!==FLOOR||state.bombs.has(cell)||state.bombs.size>=MAX_BOMBS)return null;const bombs=new Map(state.bombs);bombs.set(cell,{fuseAt:now+fuse,range});return{...state,bombs};}
function resolveTick(state,now){const grid=state.grid.slice();const bombs=new Map(state.bombs);const flames=new Map();for(const[cell,until]of state.flames)if(until>now)flames.set(cell,until);const queue=[];for(const[cell,b]of bombs)if(b.fuseAt<=now)queue.push({cell,by:null});const detonated=[];const broken=[];const burned=new Set();const parent=new Map();const find=(c)=>{while(parent.get(c)!==c)c=parent.get(c);return c;};const union=(a,b)=>{const ra=find(a);const rb=find(b);if(ra!==rb)parent.set(rb,ra);};while(queue.length){const{cell,by}=queue.shift();const bomb=bombs.get(cell);if(!bomb)continue;bombs.delete(cell);parent.set(cell,cell);if(by!==null)union(by,cell);detonated.push({cell,by});flames.set(cell,now+FLAME_MS);burned.add(cell);const[bx,by0]=xy(cell);for(const[dx,dy]of DIRS){for(let k=1;k<=bomb.range;k++){const x=bx+dx*k;const y=by0+dy*k;if(x<0||y<0||x>=COLS||y>=ROWS)break;const c=idx(x,y);if(grid[c]===SOLID)break;if(grid[c]===BRICK){grid[c]=FLOOR;broken.push(c);flames.set(c,now+FLAME_MS);burned.add(c);break;}
if(broken.includes(c))break;flames.set(c,now+FLAME_MS);burned.add(c);if(bombs.has(c))queue.push({cell:c,by:cell});else if(parent.has(c))union(cell,c);}}}
const groupsMap=new Map();for(const{cell}of detonated){const r=find(cell);if(!groupsMap.has(r))groupsMap.set(r,[]);groupsMap.get(r).push(cell);}
const groups=[...groupsMap.values()];const chain=groups.reduce((m,g)=>Math.max(m,g.length),0);return{state:{grid,bombs,flames},detonated,broken,burned:[...burned],groups,chain,total:detonated.length};}
const cellName=(cell)=>{const[x,y]=xy(cell);return String.fromCharCode(65+x)+(y+1);};function describeCell(state,cell){const what=state.flames?.has(cell)?"Feuer":state.bombs?.has(cell)?"Bombe":state.grid[cell]===SOLID?"Säule":state.grid[cell]===BRICK?"Mauer":"frei";return`${cellName(cell)}, ${what}`;}
const BEST_KEY="lmf-bomb-best";const FALLBACK={bg:"#0d0b1a",floor:"#110e22",grid:"rgb(52 245 255 / 0.07)",pillar:"#1d1740",pillarHi:"rgb(52 245 255 / 0.28)",brick:"#3b1d5e",brickHi:"#d59bf0",mortar:"#1a1030",ink:"#f3eee7",magenta:"#ff3ea5",cyan:"#34f5ff",hot:"#ffb347",bomb:"#17122c",};function mount(root,ctx={}){const motion=calmSource(ctx);const say=announcer(ctx);const store=ctx.storage?.local;const howId=nextId("pb-how");root.classList.add("probe","probe-bomb");root.tabIndex=-1;root.innerHTML=`
<div class="pb-screen" tabindex="0" role="application" aria-roledescription="Spielfeld"
aria-label="Bomberman-Nachbau, 15 mal 13 Felder" aria-describedby="${howId}">
<canvas class="pb-canvas" aria-hidden="true"></canvas>
<p class="vh" data-pb="where" aria-live="polite" aria-atomic="true"></p>
<p class="pb-hud" aria-hidden="true"><span class="pb-hud-tag">Neon-Nachbau</span><span class="pb-hud-tick">Tick <b data-pb="tick">0</b></span></p>
</div>
<div class="probe-toolbar">
<button class="button button--ghost probe-btn" type="button" data-pb="new">Neues Feld</button>
<button class="button probe-btn" type="button" data-pb="fire">Alles zünden</button>
<p class="probe-readout meta" data-pb="readout" aria-live="off">
<span>Kette: <b data-pb="chain">0</b></span>
<span>Rekord: <b data-pb="best">0</b></span>
<span>Bomben: <b data-pb="count">0</b>/${MAX_BOMBS}</span>
</p>
</div>
<p class="probe-howto" id="${howId}">Feld antippen oder mit Pfeiltasten wählen · Leertaste legt eine Bombe · Z zündet alles · R: neues Feld · Esc: raus</p>`;const screen=root.querySelector(".pb-screen");const canvas=root.querySelector("canvas");const g=canvas.getContext("2d");const $=(k)=>root.querySelector(`[data-pb="${k}"]`);const out={chain:$("chain"),best:$("best"),count:$("count"),tick:$("tick"),where:$("where")};const css=getComputedStyle(root);const P={};for(const[k,v]of Object.entries(FALLBACK))P[k]=css.getPropertyValue(`--pb-${k.replace(/[A-Z]/g,(c)=>`-${c.toLowerCase()}`)}`).trim()||v;P.mono=css.getPropertyValue("--font-mono").trim()||"monospace";let seed=195;let state=makeState(seed);let sim=0;let ticks=0;let cursor=idx(7,6);let showCursor=false;let best=Number(store?.get(BEST_KEY,0))||0;let raf=0;let last=0;let acc=0;let paused=false;let destroyed=false;let attract=null;let touched=false;const fx={particles:[],links:[],rings:[],stamp:null,shake:0};let size={w:0,h:0,c:0,ox:0,oy:0,dpr:1};out.best.textContent=best;function resize(){const w=screen.clientWidth;if(!w)return;const dpr=Math.min(2,window.devicePixelRatio||1);const c=Math.max(12,Math.min(42,Math.floor(w/COLS)));const h=c*ROWS;canvas.style.width=`${c*COLS}px`;canvas.style.height=`${h}px`;canvas.width=Math.round(c*COLS*dpr);canvas.height=Math.round(h*dpr);size={w:c*COLS,h,c,dpr};draw();}
const ro=new ResizeObserver(resize);ro.observe(screen);const busy=()=>state.bombs.size||state.flames.size||fx.particles.length||fx.links.length||fx.rings.length||fx.stamp||fx.shake>0||attract;function kick(){if(raf||paused||destroyed)return;last=performance.now();raf=requestAnimationFrame(frame);}
function frame(t){raf=0;const dt=Math.min(100,t-last);last=t;acc+=dt;while(acc>=TICK_MS){acc-=TICK_MS;sim+=TICK_MS;ticks++;step();}
stepFx(dt);draw();if(busy()&&!paused&&!destroyed)raf=requestAnimationFrame(frame);else acc=0;}
function step(){if(!state.bombs.size&&!state.flames.size){if(attract&&sim>=attract.resetAt)endAttract();return;}
const r=resolveTick(state,sim);state=r.state;if(r.total)onBlast(r);if(attract&&sim>=attract.resetAt&&!state.bombs.size)endAttract();}
function onBlast(r){out.tick.textContent=ticks;out.chain.textContent=r.chain;out.count.textContent=state.bombs.size;const calm=motion.calm;for(const{cell,by}of r.detonated){if(by!==null)fx.links.push({a:by,b:cell,t:0});fx.rings.push({cell,t:0});}
if(!calm){for(const cell of r.broken)spawnDebris(cell);fx.shake=Math.min(9,2+r.chain*1.5);}
if(r.chain>=2)fx.stamp={text:`KETTE ×${r.chain}`,t:0};if(attract){attract.resetAt=sim+1200;return;}
if(r.chain>best){best=r.chain;out.best.textContent=best;store?.set(BEST_KEY,best);}
const walls=r.broken.length===1?"1 Mauer":`${r.broken.length} Mauern`;say(r.chain>=2?`Kettenreaktion: ${r.chain} Bomben, ${walls} weg.`:`Eine Bombe, ${walls} weg.`);}
function spawnDebris(cell){const[x,y]=xy(cell);for(let i=0;i<9;i++){const a=Math.random()*Math.PI*2;const v=1.5+Math.random()*3.5;fx.particles.push({x:x+0.5,y:y+0.5,vx:Math.cos(a)*v,vy:Math.sin(a)*v-2.5,life:1,s:0.08+Math.random()*0.12});}}
function stepFx(dt){const s=dt/1000;for(const p of fx.particles){p.vy+=14*s;p.x+=p.vx*s;p.y+=p.vy*s;p.life-=s*1.6;}
fx.particles=fx.particles.filter((p)=>p.life>0);for(const l of fx.links)l.t+=dt;fx.links=fx.links.filter((l)=>l.t<900);for(const r of fx.rings)r.t+=dt;fx.rings=fx.rings.filter((r)=>r.t<420);if(fx.stamp){fx.stamp.t+=dt;if(fx.stamp.t>1100)fx.stamp=null;}
fx.shake=Math.max(0,fx.shake-dt*0.05);}
function draw(){const{c,dpr}=size;if(!c)return;const calm=motion.calm;g.setTransform(dpr,0,0,dpr,0,0);g.fillStyle=P.bg;g.fillRect(0,0,size.w,size.h);if(fx.shake>0&&!calm)g.translate((Math.random()-0.5)*fx.shake,(Math.random()-0.5)*fx.shake);for(let y=0;y<ROWS;y++){for(let x=0;x<COLS;x++){const t=state.grid[idx(x,y)];const px=x*c;const py=y*c;if(t===SOLID)drawPillar(px,py,c);else if(t===BRICK)drawBrick(px,py,c,x,y);else{g.fillStyle=(x+y)%2?P.floor:P.bg;g.fillRect(px,py,c,c);g.strokeStyle=P.grid;g.lineWidth=1;g.strokeRect(px+0.5,py+0.5,c-1,c-1);}}}
g.save();g.globalCompositeOperation=calm?"source-over":"lighter";for(const[cell,until]of state.flames){const life=calm?1:Math.max(0,(until-sim)/FLAME_MS);drawFlame(cell,life,calm);}
for(const l of fx.links){const k=Math.min(1,l.t/120);const fade=1-Math.max(0,(l.t-200)/700);const[ax,ay]=xy(l.a);const[bx,by]=xy(l.b);g.strokeStyle=P.cyan;g.globalAlpha=Math.max(0,fade);g.lineWidth=Math.max(2,c*0.12);g.lineCap="round";g.beginPath();g.moveTo((ax+0.5)*c,(ay+0.5)*c);g.lineTo((ax+0.5+(bx-ax)*k)*c,(ay+0.5+(by-ay)*k)*c);g.stroke();}
g.globalAlpha=1;if(!calm){for(const r of fx.rings){const[x,y]=xy(r.cell);const k=r.t/420;g.strokeStyle=P.hot;g.globalAlpha=1-k;g.lineWidth=2;g.beginPath();g.arc((x+0.5)*c,(y+0.5)*c,c*(0.3+k*1.1),0,Math.PI*2);g.stroke();}
g.globalAlpha=1;}
g.restore();for(const[cell,b]of state.bombs)drawBomb(cell,b,calm);g.fillStyle=P.brickHi;for(const p of fx.particles){g.globalAlpha=Math.max(0,p.life);g.fillRect(p.x*c,p.y*c,p.s*c,p.s*c);}
g.globalAlpha=1;if(showCursor)drawCursor(calm);if(fx.stamp)drawStamp(calm);g.setTransform(1,0,0,1,0,0);}
function drawPillar(px,py,c){g.fillStyle=P.pillar;g.fillRect(px,py,c,c);g.strokeStyle=P.pillarHi;g.lineWidth=Math.max(1,c*0.06);g.beginPath();g.moveTo(px+2,py+c-3);g.lineTo(px+2,py+2);g.lineTo(px+c-3,py+2);g.stroke();g.fillStyle=P.bg;g.globalAlpha=0.45;g.fillRect(px+c*0.3,py+c*0.3,c*0.4,c*0.4);g.globalAlpha=1;}
function drawBrick(px,py,c,x,y){g.fillStyle=P.brick;g.fillRect(px,py,c,c);g.strokeStyle=P.mortar;g.lineWidth=Math.max(1,c*0.05);g.beginPath();const h=c/3;for(let r=1;r<3;r++){g.moveTo(px,py+r*h);g.lineTo(px+c,py+r*h);}
for(let r=0;r<3;r++){const off=(r+x+y)%2?c/2:c/4;g.moveTo(px+off,py+r*h);g.lineTo(px+off,py+(r+1)*h);if(off<c/2){g.moveTo(px+off+c/2,py+r*h);g.lineTo(px+off+c/2,py+(r+1)*h);}}
g.stroke();g.fillStyle=P.brickHi;g.globalAlpha=0.35;g.fillRect(px+1,py+1,c-2,Math.max(1,c*0.06));g.globalAlpha=1;}
function drawFlame(cell,life,calm){const{c}=size;const[x,y]=xy(cell);const cx=(x+0.5)*c;const cy=(y+0.5)*c;if(calm){g.fillStyle=P.magenta;g.fillRect(x*c+c*0.12,y*c+c*0.12,c*0.76,c*0.76);g.fillStyle=P.ink;g.fillRect(cx-c*0.12,cy-c*0.12,c*0.24,c*0.24);return;}
const r=c*(0.55+0.25*life);const grad=g.createRadialGradient(cx,cy,0,cx,cy,r);grad.addColorStop(0,P.ink);grad.addColorStop(0.35,P.hot);grad.addColorStop(0.7,P.magenta);grad.addColorStop(1,"transparent");g.globalAlpha=Math.min(1,life*1.4);g.fillStyle=grad;g.fillRect(cx-r,cy-r,r*2,r*2);g.globalAlpha=1;}
function drawBomb(cell,b,calm){const{c}=size;const[x,y]=xy(cell);const cx=(x+0.5)*c;const cy=(y+0.54)*c;const left=Math.max(0,b.fuseAt-sim);const k=1-left/FUSE_MS;const pulse=calm?1:1+0.07*Math.sin(sim/(160-110*k))*(0.4+k);const r=c*0.32*pulse;if(!calm){const glow=g.createRadialGradient(cx,cy,r*0.6,cx,cy,r*1.9);glow.addColorStop(0,P.magenta);glow.addColorStop(1,"transparent");g.globalAlpha=0.25+0.35*k;g.fillStyle=glow;g.fillRect(cx-r*2,cy-r*2,r*4,r*4);g.globalAlpha=1;}
g.fillStyle=P.bomb;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);g.fill();g.strokeStyle=P.cyan;g.lineWidth=Math.max(1.5,c*0.07);g.stroke();g.strokeStyle=P.ink;g.globalAlpha=0.7;g.lineWidth=Math.max(1,c*0.05);g.beginPath();g.arc(cx,cy,r*0.62,Math.PI*1.1,Math.PI*1.45);g.stroke();g.globalAlpha=1;g.strokeStyle=P.magenta;g.lineWidth=Math.max(2,c*0.08);g.beginPath();g.arc(cx,cy,r+c*0.1,-Math.PI/2,-Math.PI/2+(1-k)*Math.PI*2);g.stroke();if(calm){g.fillStyle=P.ink;g.font=`600 ${Math.max(9,Math.round(c*0.3))}px ${P.mono}`;g.textAlign="center";g.textBaseline="middle";g.fillText((left/1000).toFixed(1).replace(".",","),cx,cy+1);}else{const sx=cx+r*0.7;const sy=cy-r*0.95;g.fillStyle=Math.random()<0.5?P.hot:P.ink;g.beginPath();g.arc(sx,sy,c*(0.05+Math.random()*0.05),0,Math.PI*2);g.fill();}}
function drawCursor(calm){const{c}=size;const[x,y]=xy(cursor);const px=x*c;const py=y*c;const inset=calm?2:2+Math.sin(performance.now()/180)*1.5;const l=c*0.3;g.strokeStyle=P.cyan;g.lineWidth=2;g.beginPath();const a=px+inset;const b=py+inset;const e=px+c-inset;const f=py+c-inset;g.moveTo(a,b+l);g.lineTo(a,b);g.lineTo(a+l,b);g.moveTo(e-l,b);g.lineTo(e,b);g.lineTo(e,b+l);g.moveTo(e,f-l);g.lineTo(e,f);g.lineTo(e-l,f);g.moveTo(a+l,f);g.lineTo(a,f);g.lineTo(a,f-l);g.stroke();}
function drawStamp(calm){const{t,text}=fx.stamp;const k=Math.min(1,t/260);const s=calm?1:1+0.35*(1-easeOutBack(k));const alpha=t>700?Math.max(0,1-(t-700)/400):1;const fs=Math.round(size.c*1.35);g.save();g.globalAlpha=alpha;g.translate(size.w/2,size.h/2);g.scale(s,s);g.rotate(-0.05);g.font=`800 ${fs}px ${P.mono}`;g.textAlign="center";g.textBaseline="middle";g.lineWidth=Math.max(3,fs*0.12);g.strokeStyle=P.bg;g.strokeText(text,0,0);g.fillStyle=P.ink;g.fillText(text,0,0);g.fillStyle=P.magenta;g.fillRect(-fs*3,fs*0.62,fs*6*k,Math.max(2,fs*0.08));g.restore();}
const easeOutBack=(x)=>1+2.70158*Math.pow(x-1,3)+1.70158*Math.pow(x-1,2);function place(cell,{silent=false}={}){const next=placeBomb(state,cell,sim);if(!next){if(!silent){const why=state.bombs.size>=MAX_BOMBS?`Mehr als ${MAX_BOMBS} Bomben gehen nicht.`:"Da passt keine Bombe hin.";say(why);nudge();}
return false;}
state=next;out.count.textContent=state.bombs.size;if(!silent)say(`Bombe auf Feld ${cellName(cell)}.`);kick();return true;}
function igniteAll(){if(!state.bombs.size){say("Keine Bombe auf dem Feld.");return;}
const bombs=new Map();for(const[cell,b]of state.bombs)bombs.set(cell,{...b,fuseAt:sim});state={...state,bombs};kick();}
function newField({silent=false}={}){seed=(seed*16807)%2147483647;state=makeState(seed);fx.particles=[];fx.links=[];fx.rings=[];fx.stamp=null;out.count.textContent=0;out.chain.textContent=0;if(!silent)say("Neues Feld.");draw();}
function nudge(){if(motion.calm)return;screen.animate([{transform:"translateX(0)"},{transform:"translateX(-4px)"},{transform:"translateX(3px)"},{transform:"translateX(0)"}],{duration:180,easing:"ease-out"});}
function userInput(){touched=true;paused=false;if(attract)endAttract(true);}
function startAttract(){if(touched||motion.calm||paused||destroyed)return;const saved=state;attract={resetAt:Infinity,saved};state={grid:saved.grid.slice(),bombs:new Map(),flames:new Map()};const row=[idx(5,5),idx(7,5),idx(9,5)];for(const c of row)state.grid[c]=FLOOR;state=placeBomb(state,row[0],sim,{fuse:900})??state;state=placeBomb(state,row[1],sim,{fuse:FUSE_MS*3})??state;state=placeBomb(state,row[2],sim,{fuse:FUSE_MS*3})??state;out.count.textContent=state.bombs.size;kick();}
function endAttract(immediate=false){if(!attract)return;const{saved}=attract;attract=null;state=saved;out.count.textContent=state.bombs.size;out.chain.textContent=0;if(immediate){fx.links=[];fx.rings=[];fx.particles=[];fx.stamp=null;}
draw();}
let io=null;if("IntersectionObserver"in window){io=new IntersectionObserver((records)=>{if(records.some((r)=>r.intersectionRatio>=0.6)){io.disconnect();io=null;startAttract();}},{threshold:[0.6]},);io.observe(screen);}
const cellAt=(e)=>{const r=canvas.getBoundingClientRect();const x=Math.floor(((e.clientX-r.left)/r.width)*COLS);const y=Math.floor(((e.clientY-r.top)/r.height)*ROWS);return x>=0&&y>=0&&x<COLS&&y<ROWS?idx(x,y):-1;};function onPointerDown(e){const cell=cellAt(e);if(cell<0)return;userInput();e.preventDefault();screen.focus({preventScroll:true});cursor=cell;place(cell);draw();}
function onPointerMove(e){if(e.pointerType!=="mouse")return;const cell=cellAt(e);if(cell<0||cell===cursor)return;cursor=cell;showCursor=true;if(!raf)draw();}
function onPointerLeave(){if(document.activeElement!==screen){showCursor=false;if(!raf)draw();}}
function onKey(e){if(e.altKey||e.ctrlKey||e.metaKey)return;const[x,y]=xy(cursor);const move={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(move){e.preventDefault();userInput();const nx=Math.min(COLS-1,Math.max(0,x+move[0]));const ny=Math.min(ROWS-1,Math.max(0,y+move[1]));cursor=idx(nx,ny);showCursor=true;out.where.textContent=describeCell(state,cursor);if(!raf)draw();return;}
const key=e.key.length===1?e.key.toLowerCase():e.key;if(key===" "||key==="Enter"){e.preventDefault();userInput();place(cursor);}else if(key==="z"){e.preventDefault();userInput();igniteAll();}else if(key==="r"){e.preventDefault();userInput();newField();}else if(key==="Escape"){e.preventDefault();root.focus({preventScroll:true});}}
const onFocus=()=>{showCursor=true;if(!raf)draw();};const onBlur=()=>{showCursor=false;if(!raf)draw();};const onNew=()=>{userInput();newField();};const onFire=()=>{userInput();igniteAll();};canvas.addEventListener("pointerdown",onPointerDown);canvas.addEventListener("pointermove",onPointerMove);canvas.addEventListener("pointerleave",onPointerLeave);screen.addEventListener("keydown",onKey);screen.addEventListener("focus",onFocus);screen.addEventListener("blur",onBlur);$("new").addEventListener("click",onNew);$("fire").addEventListener("click",onFire);const offCalm=motion.onCalmChange?.(()=>draw())??(()=>{});resize();return{pause(){paused=true;if(raf)cancelAnimationFrame(raf);raf=0;if(attract)endAttract(true);},resume(){paused=false;if(busy())kick();else draw();},destroy(){destroyed=true;if(raf)cancelAnimationFrame(raf);raf=0;ro.disconnect();io?.disconnect();offCalm();canvas.removeEventListener("pointerdown",onPointerDown);canvas.removeEventListener("pointermove",onPointerMove);canvas.removeEventListener("pointerleave",onPointerLeave);screen.removeEventListener("keydown",onKey);root.replaceChildren();},};}
return{get KIND(){return KIND},get CHIP(){return CHIP},get mount(){return mount}}})();
const __mixer=(()=>{const KIND="nachbau";const CHIP="Nachbau: Statt eines echten Songs singt hier diese Website, mit selbst erzeugten Tönen. Wie im Original laufen Gesang und Instrumental über zwei getrennte Regler.";const BPM=96;const BEAT=60/BPM;const BEATS_PER_LINE=8;const SONG=[{words:["Aus","Neugier.","Gemacht."],notes:[67,69,72],hold:3,chords:["C","Am"]},{words:["Ich","wollte","wissen,","ob","das","geht."],notes:[69,67,69,72,72,74],hold:2,chords:["F","G"]},{words:["So","fangen","ziemlich","viele","meiner","Projekte","an."],notes:[64,67,69,67,64,62,69],hold:1,chords:["C","Am"]},{words:["Das","Feuer","ist","noch","an."],notes:[72,69,67,69,72],hold:4,chords:["F","C"]},].map((line)=>({...line,text:line.words.join(" ")}));const CHORDS={C:{root:36,triad:[60,64,67]},Am:{root:33,triad:[57,60,64]},F:{root:29,triad:[57,60,65]},G:{root:31,triad:[59,62,67]},};const hz=(midi)=>440*Math.pow(2,(midi-69)/12);function buildScore(song=SONG){const words=[];const lead=[];const bass=[];const pad=[];song.forEach((line,li)=>{const start=li*BEATS_PER_LINE;line.words.forEach((w,wi)=>{const last=wi===line.words.length-1;const dur=last?line.hold:1;words.push({line:li,index:wi,text:w,start:start+wi,dur});lead.push({start:start+wi,dur:dur*0.92,midi:line.notes[wi]});});line.chords.forEach((name,bi)=>{const ch=CHORDS[name];const bar=start+bi*4;pad.push({start:bar,dur:4,triad:ch.triad});bass.push({start:bar,dur:0.9,midi:ch.root});bass.push({start:bar+1,dur:0.4,midi:ch.root+12});bass.push({start:bar+2,dur:0.9,midi:ch.root+7});bass.push({start:bar+3,dur:0.4,midi:ch.root+12});});});return{words,lead,bass,pad,beats:song.length*BEATS_PER_LINE};}
function mount(root,ctx={}){const motion=calmSource(ctx);const say=announcer(ctx);const score=buildScore();const LOOP=score.beats*BEAT;const ids={how:nextId("pm-how"),voc:nextId("pm-voc"),ins:nextId("pm-ins")};root.classList.add("probe","probe-mixer");root.tabIndex=-1;const linesHtml=SONG.map((line,li)=>`<p class="pm-line" data-line="${li}">${line.words.map((w,wi)=>`<span class="pm-w" data-w="${li}-${wi}">${w}</span>`).join(" ")}</p>`,).join("");root.innerHTML=`
<div class="pm-deck">
<div class="pm-screen" tabindex="0" role="group" aria-roledescription="Karaoke-Anzeige" aria-label="MelodAI-Nachbau, Karaoke-Anzeige" aria-describedby="${ids.how}">
<p class="pm-hud meta" aria-hidden="true">
<span class="pm-hud-tag">MelodAI · Nachbau</span>
<span><span data-pm="bpm">${BPM}</span> BPM · Zeile <b data-pm="lineNo">1</b>/${SONG.length}</span>
<span data-pm="clock">0:00</span>
</p>
<div class="pm-lyrics" aria-hidden="true"><div class="pm-roll">${linesHtml}</div></div>
<p class="pm-now vh" data-pm="now"></p>
<p class="pm-you" data-pm="you" hidden><span>Jetzt du.</span></p>
<div class="pm-progress" aria-hidden="true"><i data-pm="bar"></i>${SONG.map(()=>"<b></b>").join("")}</div>
</div>
<div class="pm-desk" role="group" aria-label="Mischpult">
${channel("voc","Gesang",ids.voc,80)}
${channel("ins","Instrumental",ids.ins,70)}
</div>
</div>
<div class="probe-toolbar">
<button class="button probe-btn" type="button" data-pm="play"><svg class="i" aria-hidden="true" focusable="false"><use href="#i-play"></use></svg><span data-pm="playLabel">Abspielen</span></button>
<button class="button button--ghost probe-btn" type="button" data-pm="restart">Von vorn</button>
<button class="button button--ghost probe-btn pm-sound" type="button" data-pm="sound" aria-pressed="false"><span class="pm-led" aria-hidden="true"></span>Ton an</button>
<p class="probe-readout meta pm-note" data-pm="soundnote">Ohne „Ton an“ bleibt es still.</p>
</div>
<p class="probe-howto" id="${ids.how}">Regler ziehen oder mit Pfeiltasten stellen · Leertaste auf der Anzeige: Abspielen/Pause · Gesang auf 0: jetzt singst du</p>`;function channel(key,label,id,value){return`<div class="pm-ch" data-ch="${key}">
<label class="pm-ch-label meta" for="${id}">${label}</label>
<canvas class="pm-wave" data-wave="${key}" aria-hidden="true"></canvas>
<div class="pm-fader-slot">
<input class="pm-fader" id="${id}" type="range" min="0" max="100" step="1" value="${value}" aria-valuetext="${value} Prozent" data-fader="${key}" />
</div>
<span class="pm-ch-val meta" aria-hidden="true" data-val="${key}">${value} %</span>
</div>`;}
const q=(sel)=>root.querySelector(sel);const el={screen:q(".pm-screen"),lyrics:q(".pm-lyrics"),roll:q(".pm-roll"),lines:[...root.querySelectorAll(".pm-line")],words:[...root.querySelectorAll(".pm-w")],you:q('[data-pm="you"]'),now:q('[data-pm="now"]'),lineNo:q('[data-pm="lineNo"]'),clock:q('[data-pm="clock"]'),bar:q('[data-pm="bar"]'),play:q('[data-pm="play"]'),playLabel:q('[data-pm="playLabel"]'),restart:q('[data-pm="restart"]'),sound:q('[data-pm="sound"]'),note:q('[data-pm="soundnote"]'),voc:q('[data-fader="voc"]'),ins:q('[data-fader="ins"]'),vocVal:q('[data-val="voc"]'),insVal:q('[data-val="ins"]'),waves:{voc:q('[data-wave="voc"]'),ins:q('[data-wave="ins"]')},};const css=getComputedStyle(root);const cv=(name,fallback)=>css.getPropertyValue(name).trim()||fallback;const C={voc:cv("--pm-voc","#86aeff"),ins:cv("--pm-ins","#e9c46a"),line:cv("--pm-grid","rgb(154 163 189 / 0.22)")};let playing=false;let pos=0;let originPerf=0;let raf=0;let destroyed=false;let paused=false;let attractUntil=-1;let touched=false;let activeLine=-1;let activeWord=-1;let level={voc:0.8,ins:0.7};let ac=null;let bus=null;let gains=null;let analysers=null;let schedTimer=0;let nextBeat=0;let originAudio=0;let soundOn=false;const now=()=>{if(!playing)return pos;if(soundOn&&ac)return ac.currentTime-originAudio;return performance.now()/1000-originPerf;};const loopPos=(t)=>((t%LOOP)+LOOP)%LOOP;const fmtClock=(s)=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`;function play({attract=false}={}){if(playing||destroyed)return;playing=true;originPerf=performance.now()/1000-pos;if(soundOn&&ac)startAudio();if(!attract)attractUntil=-1;setTransport(true);loop();}
function stop(){if(!playing)return;pos=now();playing=false;stopAudio();setTransport(false);if(raf)cancelAnimationFrame(raf);raf=0;render(true);}
function setTransport(on){el.playLabel.textContent=on?"Pause":"Abspielen";el.play.querySelector("use").setAttribute("href",on?"#i-pause":"#i-play");emit({playing:on});}
const emit=(detail)=>root.dispatchEvent(new CustomEvent("lmf:probe",{bubbles:true,detail}));function restart(){const was=playing;if(was)stop();pos=0;activeLine=-1;activeWord=-1;for(const w of el.words)resetWord(w);render(true);if(was)play();}
function loop(){raf=0;if(!playing||destroyed||paused)return;const t=now();if(attractUntil>=0&&t/BEAT>=attractUntil){stop();attractUntil=-1;return;}
render();raf=requestAnimationFrame(loop);}
function ensureAudio(){if(ac)return true;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;ac=new AC();const master=ac.createGain();master.gain.value=0.15;master.connect(ac.destination);gains={voc:ac.createGain(),ins:ac.createGain()};analysers={voc:ac.createAnalyser(),ins:ac.createAnalyser()};for(const k of["voc","ins"]){analysers[k].fftSize=1024;gains[k].gain.value=curve(level[k]);gains[k].connect(analysers[k]);analysers[k].connect(master);}
return true;}
const curve=(v)=>v*v;function startAudio(){if(!ac)return;ac.resume?.();bus={voc:ac.createGain(),ins:ac.createGain()};bus.voc.connect(gains.voc);bus.ins.connect(gains.ins);const t=now();originAudio=ac.currentTime-t;nextBeat=Math.floor(t/BEAT);schedule();clearInterval(schedTimer);schedTimer=setInterval(schedule,25);}
function stopAudio(){clearInterval(schedTimer);schedTimer=0;if(bus&&ac){const old=bus;const t=ac.currentTime;for(const g of[old.voc,old.ins]){g.gain.setValueAtTime(g.gain.value,t);g.gain.linearRampToValueAtTime(0,t+0.04);}
const ctxAt=ac;setTimeout(()=>{old.voc.disconnect();old.ins.disconnect();if(!bus&&ac===ctxAt&&ac.state==="running")ac.suspend?.();},80);}else if(ac&&ac.state==="running")ac.suspend?.();bus=null;}
function schedule(){if(!ac||!bus||!playing)return;const horizon=ac.currentTime+0.12;while(originAudio+nextBeat*BEAT<horizon){const b=nextBeat;const inLoop=((b%score.beats)+score.beats)%score.beats;const at=originAudio+b*BEAT;for(const n of score.lead)if(n.start===inLoop)voice(at,n.dur*BEAT,hz(n.midi));for(const n of score.bass)if(Math.floor(n.start)===inLoop)bassNote(at+(n.start-inLoop)*BEAT,n.dur*BEAT,hz(n.midi));for(const n of score.pad)if(n.start===inLoop)padChord(at,n.dur*BEAT,n.triad.map(hz));nextBeat++;}}
function env(g,at,dur,peak,a=0.02,r=0.08){const t0=Math.max(at,ac.currentTime);g.gain.setValueAtTime(0,t0);g.gain.linearRampToValueAtTime(peak,t0+a);g.gain.setValueAtTime(peak,t0+Math.max(a,dur-r));g.gain.linearRampToValueAtTime(0,t0+dur);}
function voice(at,dur,f){const o=ac.createOscillator();o.type="sine";o.frequency.value=f;const lfo=ac.createOscillator();lfo.frequency.value=5.5;const depth=ac.createGain();depth.gain.setValueAtTime(0,at);depth.gain.linearRampToValueAtTime(f*0.012,at+Math.min(0.25,dur));lfo.connect(depth).connect(o.frequency);const g=ac.createGain();env(g,at,dur,0.9,0.03,0.09);o.connect(g).connect(bus.voc);o.start(at);lfo.start(at);o.stop(at+dur+0.02);lfo.stop(at+dur+0.02);}
function bassNote(at,dur,f){const o=ac.createOscillator();o.type="triangle";o.frequency.value=f;const g=ac.createGain();env(g,at,dur,0.9,0.01,0.06);o.connect(g).connect(bus.ins);o.start(at);o.stop(at+dur+0.02);}
function padChord(at,dur,fs){const lp=ac.createBiquadFilter();lp.type="lowpass";lp.frequency.value=1200;lp.Q.value=0.5;const g=ac.createGain();env(g,at,dur,0.16,0.12,0.3);lp.connect(g).connect(bus.ins);for(const f of fs){const o=ac.createOscillator();o.type="square";o.frequency.value=f;o.detune.value=(Math.random()-0.5)*8;o.connect(lp);o.start(at);o.stop(at+dur+0.02);}}
function setSound(on){if(on&&!ensureAudio()){el.note.textContent="Dein Browser kann hier keinen Ton erzeugen.";return;}
soundOn=on;el.sound.setAttribute("aria-pressed",String(on));el.note.textContent=on?"Ton läuft. Synthetisiert, keine Aufnahme.":"Ohne „Ton an“ bleibt es still.";if(on){if(playing){const t=now();originPerf=performance.now()/1000-t;pos=t;startAudio();}else play();}else{if(playing){const t=now();stopAudio();originPerf=performance.now()/1000-t;}
ac?.suspend?.();}
say(on?"Ton an.":"Ton aus.");}
function onFader(e){const key=e.target.dataset.fader;const v=Number(e.target.value);level[key]=v/100;e.target.setAttribute("aria-valuetext",`${v} Prozent`);(key==="voc"?el.vocVal:el.insVal).textContent=`${v} %`;root.style.setProperty(`--pm-${key}-level`,String(v/100));if(gains)gains[key].gain.setTargetAtTime(curve(level[key]),ac.currentTime,0.015);if(key==="voc")setSilent(v===0);touched=true;if(!raf)render(true);}
function setSilent(silent){if(el.you.hidden===!silent)return;el.you.hidden=!silent;el.lyrics.classList.toggle("is-silent",silent);if(silent){say("Gesang aus. Jetzt du.");if(!motion.calm)el.you.animate([{opacity:0,transform:"scale(1.08)"},{opacity:1,transform:"none"}],{duration:420,easing:"cubic-bezier(.34,1.56,.64,1)"});}}
function resetWord(w){w.style.backgroundPosition="";w.classList.remove("is-sung","is-on");}
function render(force=false){const t=now();const lt=loopPos(t);const beat=lt/BEAT;const calm=motion.calm;el.clock.textContent=fmtClock(lt);el.bar.style.transform=`scaleX(${lt/LOOP})`;let wIndex=-1;for(let i=0;i<score.words.length;i++){const w=score.words[i];if(beat>=w.start&&beat<w.start+Math.max(w.dur,1))wIndex=i;}
const line=Math.min(SONG.length-1,Math.floor(beat/BEATS_PER_LINE));if(line!==activeLine||force)setLine(line,force);score.words.forEach((w,i)=>{const span=el.words[i];if(w.line!==line){if(span.classList.contains("is-sung")||span.classList.contains("is-on"))resetWord(span);return;}
const k=(beat-w.start)/w.dur;if(k>=1){span.classList.add("is-sung");span.classList.remove("is-on");span.style.backgroundPosition="0% 0";}else if(k>=0){span.classList.add("is-on");span.style.backgroundPosition=calm?"0% 0":`${(1-k)*100}% 0`;}else resetWord(span);});if(wIndex!==activeWord){activeWord=wIndex;}
drawWaves(t,beat);}
function setLine(line,instant){const prev=activeLine;activeLine=line;el.lineNo.textContent=line+1;el.lines.forEach((p,i)=>{p.classList.toggle("is-active",i===line);p.classList.toggle("is-past",i<line);});const target=el.lines[line];const offset=target.offsetTop+target.offsetHeight/2-el.lyrics.clientHeight/2;const calm=motion.calm;el.roll.style.transition=instant||calm||prev===-1?"none":"";el.roll.style.transform=`translateY(${-Math.max(0,offset)}px)`;if(playing){el.now.textContent=SONG[line].text;if(line!==prev)emit({playing,line});}}
const waveCtx={};function sizeWaves(){for(const k of["voc","ins"]){const c=el.waves[k];const dpr=Math.min(2,devicePixelRatio||1);const w=c.clientWidth||120;const h=c.clientHeight||40;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);waveCtx[k]={g:c.getContext("2d"),w,h,dpr};}}
const buf=new Uint8Array(1024);function drawWaves(t,beat){const calm=motion.calm;for(const k of["voc","ins"]){const W=waveCtx[k];if(!W)continue;const{g,w,h,dpr}=W;g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);g.strokeStyle=C.line;g.lineWidth=1;g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke();g.strokeStyle=C[k];g.lineWidth=1.6;g.beginPath();if(soundOn&&analysers&&playing){analysers[k].getByteTimeDomainData(buf);const step=buf.length/w;for(let x=0;x<w;x++){const v=(buf[Math.floor(x*step)]-128)/128;const y=h/2+v*h*1.6;x?g.lineTo(x,y):g.moveTo(x,y);}}else{const amp=envelope(k,beat)*level[k]*(playing?1:0.25);const phase=calm||!playing?0:t*6;const cycles=k==="voc"?3+((activeWord*7)%4):2;for(let x=0;x<=w;x++){const u=x/w;let v=Math.sin(u*Math.PI*2*cycles+phase);if(k==="ins")v=0.6*Math.sign(Math.sin(u*Math.PI*2*3+phase))*0.5+0.5*Math.sin(u*Math.PI*2+phase*0.5);const y=h/2+v*amp*(h/2-3)*Math.sin(u*Math.PI);x?g.lineTo(x,y):g.moveTo(x,y);}}
g.stroke();}}
function envelope(k,beat){const lb=((beat%score.beats)+score.beats)%score.beats;if(k==="voc"){const n=score.lead.find((n)=>lb>=n.start&&lb<n.start+n.dur);if(!n)return 0.05;const into=(lb-n.start)/n.dur;return 0.35+0.65*Math.min(1,into*8)*(1-into*0.3);}
const into=lb%1;return 0.55+0.35*(1-into);}
const onPlay=()=>{touched=true;paused=false;playing?stop():play();say(playing?"Läuft.":"Pause.");};const onRestart=()=>{touched=true;paused=false;restart();};const onSound=()=>{touched=true;paused=false;setSound(!soundOn);};const onKey=(e)=>{if(e.key===" "&&e.target===el.screen){e.preventDefault();onPlay();}else if(e.key==="Escape"&&document.activeElement!==root){e.preventDefault();root.focus({preventScroll:true});}};el.play.addEventListener("click",onPlay);el.restart.addEventListener("click",onRestart);el.sound.addEventListener("click",onSound);el.voc.addEventListener("input",onFader);el.ins.addEventListener("input",onFader);root.addEventListener("keydown",onKey);const ro=new ResizeObserver(()=>{sizeWaves();setLine(Math.max(0,activeLine),true);render(true);});ro.observe(el.screen);const offCalm=motion.onCalmChange?.(()=>render(true))??(()=>{});let io=null;if("IntersectionObserver"in window){io=new IntersectionObserver((rec)=>{if(!rec.some((r)=>r.intersectionRatio>=0.6))return;io.disconnect();io=null;if(touched||motion.calm||paused||playing)return;attractUntil=BEATS_PER_LINE-0.5;play({attract:true});},{threshold:[0.6]},);io.observe(el.screen);}
let away=null;if("IntersectionObserver"in window){away=new IntersectionObserver((rec)=>{if(rec.some((r)=>!r.isIntersecting)&&playing)stop();});away.observe(el.screen);}
const onVis=()=>{if(document.hidden&&playing)stop();};document.addEventListener("visibilitychange",onVis);sizeWaves();setLine(0,true);render(true);root.__probe={get audio(){return ac;},get playing(){return playing;},};return{pause(){paused=true;if(playing)stop();},resume(){paused=false;},destroy(){destroyed=true;if(playing)emit({playing:false});playing=false;if(raf)cancelAnimationFrame(raf);raf=0;clearInterval(schedTimer);schedTimer=0;io?.disconnect();away?.disconnect();document.removeEventListener("visibilitychange",onVis);ro.disconnect();offCalm();root.removeEventListener("keydown",onKey);if(ac){try{ac.close();}catch{}}
ac=null;root.replaceChildren();delete root.__probe;},};}
return{get KIND(){return KIND},get CHIP(){return CHIP},get mount(){return mount}}})();
