/**
 * Probestück · Jahresregler (BeatGuessr)  [WP4]  · Echt (Daten) · spec §5.7e (P2)
 *
 * Reads data/probes/beatguessr.json (generated by scripts/snapshot-beatguessr.mjs from
 * loggel.github.io/BeatGuessr/data/songs.json) and the decade colours from beatguessr.meta.json
 * (copied from BeatGuessr's css/style.css). No audio, no covers, no Spotify links.
 */

import { nextId } from "./index.js";

export const KIND = "echt";
export let CHIP = "Echt: die Jahre und Etiketten aus dem Spiel.";


export async function mount(root, ctx = {}) {
  const [years, meta] = await Promise.all([
    fetch(new URL("data/probes/beatguessr.json", document.baseURI)).then((r) => (r.ok ? r.json() : null)),
    fetch(new URL("data/probes/beatguessr.meta.json", document.baseURI)).then((r) => (r.ok ? r.json() : null)).catch(() => null),
  ]);
  if (!Array.isArray(years) || !years.length) throw new Error("beatguessr.json fehlt");
  const songs = years.reduce((n, y) => n + (y.songs?.length ?? 0), 0);
  CHIP = `Echt: die Jahre und Etiketten aus dem Spiel (${new Intl.NumberFormat("de-DE").format(songs)} Songs).`;
  const colours = meta?.decadeColours ?? {};
  const first = years[0].year;
  const last = years[years.length - 1].year;
  const id = nextId("pj");

  root.classList.add("probe", "probe-jahr");
  root.tabIndex = -1;
  root.innerHTML = `
    <label class="pj-label meta" for="${id}">Jahr wählen</label>
    <input class="pj-range" id="${id}" type="range" min="${first}" max="${last}" step="1" value="${first}" />
    <div class="pj-band" aria-hidden="true"></div>
    <p class="pj-year" aria-live="polite"><span data-pj="year"></span> <em data-pj="context"></em></p>
    <ul class="pj-songs" data-pj="songs"></ul>`;
  const input = root.querySelector("input");
  const out = { year: root.querySelector('[data-pj="year"]'), context: root.querySelector('[data-pj="context"]'), songs: root.querySelector('[data-pj="songs"]') };

  function update() {
    const y = years.find((e) => e.year === Number(input.value));
    if (!y) return;
    out.year.textContent = String(y.year);
    out.context.textContent = y.context ? `· ${y.context}` : "";
    const decade = `${String(Math.floor(y.year / 10) * 10).slice(2)}s`;
    if (colours[decade]) root.style.setProperty("--pj-colour", colours[decade]);
    out.songs.replaceChildren(
      ...(y.songs ?? []).slice(0, 2).map(([title, artist]) => {
        const li = document.createElement("li");
        li.lang = "en";
        li.textContent = `${title} · ${artist}`;
        return li;
      }),
    );
    input.setAttribute("aria-valuetext", `${y.year}${y.context ? `, ${y.context}` : ""}`);
  }
  input.addEventListener("input", update);
  update();
  return {
    pause() {},
    resume() {},
    destroy() {
      input.removeEventListener("input", update);
      root.replaceChildren();
    },
  };
}
