/**
 * GENERATED by scripts/make-tools.mjs — do not edit by hand.
 * Werkzeugwand: [tool, number of projects that use it], counted from details.stack (see werkstatt.js).
 */
export const TOOLS = [["JavaScript",15],["CSS",11],["Docker",11],["GitHub Pages",11],["TypeScript",11],["HTML",8],["Vite",8],["Next.js",7],["SQLite",7],["Three.js",7],["Node.js",6],["Tailwind CSS",6],["React",5],["Python",4],["Flask",3],["WebSocket",3],["BlurHash",2],["Framer Motion",2]];
