/**
 * GENERATED by scripts/make-zr-sprite.mjs — do not edit by hand.
 * The Zeitraffer's portfolio chips: one strip of 80 × 50 px cells (2× the 40 × 25 chip).
 */
export const ZR_SPRITE = {"src":"assets/img/thumbs/zr-sprite.webp","n":23,"cells":{"assets/img/Arcanum.webp":0,"assets/img/BeatGuessr.webp":1,"assets/img/Bomberman.webp":2,"assets/img/BulliDrive.webp":3,"assets/img/CoopSudoku.webp":4,"assets/img/CoronaBoard.webp":5,"assets/img/JetLoopReactor.webp":6,"assets/img/Kniffel.webp":7,"assets/img/LearnAI.webp":8,"assets/img/LoggeRythm.webp":9,"assets/img/MelodAI-player.webp":10,"assets/img/Oilbert.webp":11,"assets/img/PalatinaFilms.webp":12,"assets/img/PowerPointKaraoke.webp":13,"assets/img/Setlist.webp":14,"assets/img/ShareXAfterimage.webp":15,"assets/img/ShareXCaptureEngine.webp":16,"assets/img/ShareXWin98.webp":17,"assets/img/SpotifyViz.webp":18,"assets/img/Transcripator.webp":19,"assets/img/VollOMeter.webp":20,"assets/img/VoxelBlitz.webp":21,"assets/img/spyfall.webp":22}};
