#!/usr/bin/env node
/**
 * Regenerates gallery/index.html as a JS-free contact sheet (spec §2.12).  [WP5]
 *
 *   node scripts/build-gallery.mjs            (npm run gallery)
 *
 * Input: gallery/assets/data/images.json (order = archive order) + the photo file names
 * (IMG_YYYYMMDD_HHMMSS) + the pixel size read from each small/*.webp header.
 * Output: one <section> per night („Nacht {nn} · {Wochentag}, {dd.mm.yyyy}“, a photo taken
 * before 12:00 belongs to the previous evening), each with a <div class="photo-grid"> of
 * frames: archive number „{nn}A“ + the time from the file name. Every frame links to the
 * large JPG and has the anchor id „foto-{nn}“ (the Nachtuhr on the start page links there).
 * No <script> on the page. No place names, no EXIF beyond the file name, no GPS.
 */
import { readFile, writeFile, open } from "node:fs/promises";
import { parsePhotoName, nightOf, nights, photoNames, formatDate } from "../js/lib/derive.js";
import { weekday } from "../js/lib/format.js";

const ROOT = new URL("../", import.meta.url);
const GALLERY = new URL("gallery/", ROOT);
const esc = (s) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const pad = (n) => String(n).padStart(2, "0");

/** Width/height from a WebP header (VP8, VP8L or VP8X). */
async function webpSize(url) {
  const fh = await open(url, "r");
  try {
    const buf = Buffer.alloc(32);
    await fh.read(buf, 0, 32, 0);
    if (buf.toString("ascii", 0, 4) !== "RIFF" || buf.toString("ascii", 8, 12) !== "WEBP") return null;
    const chunk = buf.toString("ascii", 12, 16);
    if (chunk === "VP8X") return { w: 1 + buf.readUIntLE(24, 3), h: 1 + buf.readUIntLE(27, 3) };
    if (chunk === "VP8 ") return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
    if (chunk === "VP8L") {
      const b = buf.readUInt32LE(21);
      return { w: (b & 0x3fff) + 1, h: ((b >> 14) & 0x3fff) + 1 };
    }
  } finally {
    await fh.close();
  }
  return null;
}

const images = JSON.parse(await readFile(new URL("assets/data/images.json", GALLERY), "utf8"));
const names = photoNames(images);
const nightKeys = nights(names);

const photos = [];
for (const [i, name] of names.entries()) {
  const p = parsePhotoName(name);
  if (!p) throw new Error(`Unexpected file name: ${name}`);
  const size = (await webpSize(new URL(`assets/img/small/${name}.webp`, GALLERY))) ?? { w: 400, h: 300 };
  photos.push({ name, nn: pad(i + 1), ...p, night: nightKeys.indexOf(nightOf(name)) + 1, nightKey: nightOf(name), ...size });
}

const first = photos.map((p) => p.date).sort()[0];
const last = photos.map((p) => p.date).sort().at(-1);
const autumn = first.slice(0, 4) === last.slice(0, 4) && first.slice(5) >= "09-22" && last.slice(5) <= "12-21";
const lead = `Nachts mit dem Handy${autumn ? `, Herbst ${first.slice(0, 4)}` : ""}. ${photos.length} Aufnahmen aus ${nightKeys.length} Nächten.`;

function frame(p, eager) {
  const ar = (p.w / p.h).toFixed(3);
  return `<a id="foto-${p.nn}" class="frame" href="assets/img/large/${p.name}.jpg" style="--ar:${ar}" target="_blank" rel="noopener noreferrer"><img src="assets/img/small/${p.name}.webp" alt="Galerieaufnahme ${p.nn}" width="${p.w}" height="${p.h}"${eager ? "" : ` loading="lazy"`} decoding="async"><span class="frame-edge" aria-hidden="true">${p.nn}A</span><span class="frame-time"><span class="vh">, aufgenommen um </span><time datetime="${p.date}T${p.time}">${p.time}</time></span><span class="vh"> (öffnet neue Seite)</span></a>`;
}

let count = 0;
const sections = nightKeys.map((key, n) => {
  const list = photos.filter((p) => p.nightKey === key);
  const nn = pad(n + 1);
  const times = list.length === 1 ? list[0].time : `${list[0].time}–${list.at(-1).time}`;
  const frames = list.map((p) => frame(p, count++ < 6)).join("\n");
  return `<section class="night" aria-labelledby="nacht-${nn}">
<header class="night-head"><h2 id="nacht-${nn}">Nacht ${nn} · ${weekday(key)}, ${formatDate(key)}</h2><p class="night-meta">${list.length} ${list.length === 1 ? "Aufnahme" : "Aufnahmen"} · ${times} Uhr</p></header>
<div class="photo-grid">
${frames}
</div>
</section>`;
});

const index = nightKeys.map((key, n) => `<li><a href="#nacht-${pad(n + 1)}"><span class="index-no">${pad(n + 1)}</span> ${formatDate(key, "dayMonth")}</a></li>`).join("");

const page = `<!doctype html>
<!-- Generated by scripts/build-gallery.mjs from gallery/assets/data/images.json. Do not edit by hand. -->
<html lang="de" class="screen">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>Abseits der Tabs · Fotoarchiv · Logge Media Forge</title>
    <meta name="description" content="${esc(lead)} Das Fotoarchiv von Logge Media Forge." />
    <meta name="theme-color" content="#0e0c0b" />
    <link rel="icon" href="../favicon.svg" type="image/svg+xml" />
    <link rel="preload" href="../assets/fonts/InstrumentSerif-Regular.woff2" as="font" type="font/woff2" crossorigin />
    <link rel="stylesheet" href="../css/tokens.css" />
    <link rel="stylesheet" href="css/gallery.css" />
  </head>
  <body>
    <a class="skip-link" href="#main-content">Zum Inhalt</a>
    <header class="g-header">
      <a class="g-brand" href="../"><img src="../assets/svg/logo.svg" alt="" width="54" height="33" /><span>Logge<br />Media Forge</span><span class="vh">, zur Startseite</span></a>
      <a class="g-back" href="../#abseits">← Zurück zur Werkstatt</a>
    </header>
    <main id="main-content">
      <div class="g-intro">
        <p class="g-eyebrow">LMF / Das Fotoarchiv</p>
        <h1>Abseits der Tabs.</h1>
        <p class="g-lead">${esc(lead)} Klick öffnet die große Version.</p>
        <p class="g-note">Die Uhrzeiten stammen aus den Dateinamen. Die Nummern (01A …) sind die Reihenfolge im Archiv.</p>
      </div>
      <nav class="g-index" aria-label="Nächte">
        <ol role="list">${index}</ol>
      </nav>
${sections.join("\n")}
    </main>
    <footer class="g-footer">
      <a href="../#abseits">← Zurück zur Werkstatt</a>
      <p>Logge Media Forge · Aus Neugier. Gemacht.</p>
    </footer>
  </body>
</html>
`;

await writeFile(new URL("index.html", GALLERY), page);
console.log(`gallery/index.html: ${photos.length} photos, ${nightKeys.length} nights, ${(page.length / 1024).toFixed(1)} KB`);
