#!/usr/bin/env node
/**
 * scripts/make-tools.mjs — the Werkzeugwand counts, computed once at build time  [WP5]
 *
 * The wall shows the top tools across all code projects, counted from every details file
 * (data/details/<id>.json → stack). Counting in the browser meant fetching all 43 details files
 * on a plain scroll; this script counts in Node with the same pure functions and writes a tiny
 * generated module the Werkstatt imports:
 *
 *   js/render/tools.js     export const TOOLS = [["TypeScript", 20], …]   (top 18, sorted)
 *
 * Re-run after changing projects or details (npm run import):  node scripts/make-tools.mjs
 * tests/chronik.spec.js compares the wall with a fresh Node computation, so a stale file fails.
 */
import { existsSync, writeFileSync } from "node:fs";
import { loadDataFs, ROOT } from "./lib/node-data.mjs";

const OUT = new URL("js/render/tools.js", ROOT);
// werkstatt.js imports the generated module, so it has to exist before werkstatt.js is loaded.
if (!existsSync(OUT)) writeFileSync(OUT, "export const TOOLS = [];\n");
const { wallTools } = await import("../js/sections/werkstatt.js");

const data = await loadDataFs();
if (data.failed.length) throw new Error(`Data files not loaded: ${data.failed.join(", ")}`);
const tools = wallTools(data.projects, data.detailsById).map((t) => [t.tool, t.count]);
writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/make-tools.mjs — do not edit by hand.
 * Werkzeugwand: [tool, number of projects that use it], counted from details.stack (see werkstatt.js).
 */
export const TOOLS = ${JSON.stringify(tools)};
`,
);
console.log(`${tools.length} tools → js/render/tools.js`);
