#!/usr/bin/env node
/**
 * scripts/make-thumbs.mjs — plate thumbnails (dev only; outputs are committed)  [WP2, review fix]
 *
 * Plates in „Noch warm“ and the Lager are 300–420 CSS px wide, but their screenshots are up to
 * 2560 px. This script writes 640 w and 960 w WebP copies next to them and a tiny generated module
 * the pure plate renderer reads for `srcset`:
 *
 *   assets/img/thumbs/<Name>-640.webp, <Name>-960.webp   (only widths smaller than the original)
 *   js/render/thumbs.js                                   export const THUMBS = { "<image>": [640, 960] }
 *
 * Needs `cwebp` (libwebp) on PATH. Originals are never touched or deleted. Re-run after adding or
 * swapping a project image:  node scripts/make-thumbs.mjs
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const OUT = join(ROOT, "assets/img/thumbs");
const WIDTHS = [640, 960];
const QUALITY = "72";

const raw = JSON.parse(readFileSync(join(ROOT, "data/projects.json"), "utf8"));
const projects = Array.isArray(raw) ? raw : raw.projects;
const images = [...new Set(projects.map((p) => p.image).filter(Boolean))];

/** Pixel width from the WebP header (VP8, VP8L, VP8X). */
function webpWidth(file) {
  const b = readFileSync(file);
  const chunk = b.toString("ascii", 12, 16);
  if (chunk === "VP8X") return 1 + b.readUIntLE(24, 3);
  if (chunk === "VP8L") return 1 + (b.readUInt16LE(21) & 0x3fff);
  if (chunk === "VP8 ") return b.readUInt16LE(26) & 0x3fff;
  return 0;
}

mkdirSync(OUT, { recursive: true });
const map = {};
let before = 0;
let after = 0;
for (const image of images) {
  const src = join(ROOT, image);
  if (!existsSync(src) || extname(src) !== ".webp") continue;
  const width = webpWidth(src);
  const sizes = WIDTHS.filter((w) => w < width - 40);
  if (!sizes.length) continue;
  for (const w of sizes) {
    const out = join(OUT, `${basename(src, ".webp")}-${w}.webp`);
    if (!existsSync(out) || statSync(out).mtimeMs < statSync(src).mtimeMs) {
      execFileSync("cwebp", ["-quiet", "-q", QUALITY, "-m", "6", "-sharp_yuv", "-resize", String(w), "0", src, "-o", out]);
    }
  }
  map[image] = sizes;
  before += statSync(src).size;
  after += statSync(join(OUT, `${basename(src, ".webp")}-${sizes[0]}.webp`)).size;
}

const body = `/**
 * GENERATED by scripts/make-thumbs.mjs — do not edit by hand.
 * image → available thumbnail widths in assets/img/thumbs/<Name>-<w>.webp (all smaller than the original).
 */
export const THUMBS = ${JSON.stringify(map)};
`;
writeFileSync(join(ROOT, "js/render/thumbs.js"), body);
console.log(`${Object.keys(map).length} images → thumbs; smallest set ${(after / 1024).toFixed(0)} KB vs originals ${(before / 1024).toFixed(0)} KB`);
