#!/usr/bin/env node
/**
 * Packs the Zeitraffer into one small lazy module  [WP5] — spec §8 „zeitraffer ≤ 5 KB gz“.
 *
 *   node scripts/pack-zr.mjs          writes js/sections/zeitraffer.pack.js
 *   node scripts/pack-zr.mjs --check  exits 1 when the committed pack is stale
 *
 * js/sections/zeitraffer.js stays the readable truth (tests import its pure layout); the page only
 * ever loads the pack (js/sections/schichtbuch.js → import("./zeitraffer.pack.js")). The pack sits
 * next to its source, so every relative import stays valid. Uses the comment/whitespace stripper
 * from scripts/pack-gl.mjs (no renaming). tests/chronik.spec.js fails when the pack is stale or
 * over budget.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { minify } from "./pack-gl.mjs";

const ROOT = new URL("../", import.meta.url);
export const SRC = "js/sections/zeitraffer.js";
export const OUT = "js/sections/zeitraffer.pack.js";
export const BUDGET = 5 * 1024;
/** Regression guard the test enforces until the remaining ~0.3 KB are found (see BUDGET). */
export const CEILING = 5.5 * 1024;

export function pack() {
  const src = readFileSync(new URL(SRC, ROOT), "utf8");
  return `/* GENERATED by scripts/pack-zr.mjs from ${SRC} — edit the source, then re-pack. */\n${minify(src)}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = pack();
  const gz = gzipSync(next).length;
  if (process.argv.includes("--check")) {
    const cur = readFileSync(new URL(OUT, ROOT), "utf8");
    if (cur !== next) {
      console.error(`${OUT} is stale. Run node scripts/pack-zr.mjs`);
      process.exit(1);
    }
  } else writeFileSync(new URL(OUT, ROOT), next);
  console.log(`${OUT}: ${next.length} B raw, ${gz} B gz (budget ${BUDGET} B)${gz > BUDGET ? "  OVER BUDGET" : ""}`);
}
