// Generated by scripts/pack-gl.mjs from js/gl/esse.js, shaders.js, gl.js, sparks.js. Do not edit; edit the sources and re-run it.
import{layout,buildEmbers,emberBuffer,emberX,emberY,densityRow}from"../sections/esse-embers.js";
import{HEAT,TEMPER,rgb01}from"../lib/palette.js";
const __gljs=(()=>{function program(gl,vs,fs){const p=gl.createProgram();for(const[type,src]of[[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)&&!gl.isContextLost())throw new Error(gl.getShaderInfoLog(s)||"shader");gl.attachShader(p,s);gl.deleteShader(s);}
gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS)&&!gl.isContextLost())throw new Error(gl.getProgramInfoLog(p)||"link");const u={};const n=gl.getProgramParameter(p,gl.ACTIVE_UNIFORMS)||0;for(let i=0;i<n;i++){const name=gl.getActiveUniform(p,i).name.replace(/\[0\]$/,"");u[name]=gl.getUniformLocation(p,name);}
return{p,u};}
function texture(gl,o){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);if(o.image)gl.texImage2D(gl.TEXTURE_2D,0,o.internal,o.format,o.type,o.image);else gl.texImage2D(gl.TEXTURE_2D,0,o.internal,o.w,o.h,0,o.format,o.type,o.data??null);const f=o.filter??gl.LINEAR;const w=o.wrap??gl.CLAMP_TO_EDGE;gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,f);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,f);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,w);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,w);return t;}
function framebuffer(gl,tex){const f=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,f);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);const ok=gl.checkFramebufferStatus(gl.FRAMEBUFFER)===gl.FRAMEBUFFER_COMPLETE;gl.bindFramebuffer(gl.FRAMEBUFFER,null);if(!ok)gl.deleteFramebuffer(f);return ok?f:null;}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.decoding="async";img.onload=()=>resolve(img);img.onerror=()=>reject(new Error(`image: ${src}`));img.src=src;});}
return{program,texture,framebuffer,loadImage}})();
const __shadersjs=(()=>{const HEAD="#version 300 es\nprecision highp float;\n";const RAMP=`uniform vec3 R[6];
vec3 ramp(float x){x=clamp(x,0.,1.)*5.;float i=min(floor(x),4.);int j=int(i);return mix(R[j],R[j+1],x-i);}
vec3 tone(vec3 c){return pow(1.-exp(-max(c,0.)),vec3(.4545));}
`;const NOISE=`float h1(vec2 p){vec3 a=fract(p.xyx*.1031);a+=dot(a,a.yzx+33.33);return fract((a.x+a.y)*a.z);}
vec2 h2(vec2 p){vec3 a=fract(p.xyx*vec3(.1031,.103,.0973));a+=dot(a,a.yzx+33.33);return fract((a.xx+a.yz)*a.zy);}
float n2(vec2 p){vec2 i=floor(p),f=fract(p);f*=f*(3.-2.*f);return mix(mix(h1(i),h1(i+vec2(1,0)),f.x),mix(h1(i+vec2(0,1)),h1(i+1.),f.x),f.y);}
float fbm(vec2 p){float s=0.,a=.5;for(int i=0;i<4;i++){s+=a*n2(p);p=p*2.03+vec2(1.7,9.2);a*=.5;}return s;}
`;const TRI=HEAD+"out vec2 v;void main(){vec2 p=vec2(gl_VertexID&1,gl_VertexID>>1)*2.;v=p;gl_Position=vec4(p*2.-1.,0.,1.);}";const HEAT=HEAD+`in vec2 v;out vec4 o;uniform sampler2D T;uniform vec2 px;uniform vec3 k;uniform vec4 S[4];uniform float A;
void main(){vec2 u=v-vec2(0.,px.y*.6);
vec2 h=texture(T,u).rg*.36+(texture(T,u+vec2(px.x,0.)).rg+texture(T,u-vec2(px.x,0.)).rg+texture(T,u+vec2(0.,px.y)).rg+texture(T,u-vec2(0.,px.y)).rg)*.16;
h.r=max(h.r*k.x-k.z,0.);h.g=max(max(h.g*k.y-k.z,0.),h.r);
for(int i=0;i<4;i++){vec2 d=v-S[i].xy;d.x*=A;h.r+=S[i].w*exp(-dot(d,d)/(S[i].z*S[i].z));}
o=vec4(min(h,vec2(3.)),0.,1.);}`;const MAIN=HEAD+RAMP+NOISE+`in vec2 v;out vec4 o;uniform sampler2D H,D,L;uniform vec4 G,M,K,F;uniform vec3 P[3];
vec3 vor(vec2 c){vec2 i=floor(c),f=fract(c);float a=8.,b=8.;vec2 id=i;
for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){vec2 g=vec2(x,y);vec2 r=g+h2(i+g)*.85-f;float d=dot(r,r);if(d<a){b=a;a=d;id=i+g;}else if(d<b)b=d;}
return vec3(sqrt(a),sqrt(b),h1(id*1.7));}
float sdb(vec2 p,vec2 b,float r){vec2 q=abs(p)-b+r;return length(max(q,0.))+min(max(q.x,q.y),0.)-r;}
float logo(vec2 q){vec2 u=vec2(.5+q.x*.4375,.5-q.y*.6731);vec2 e=max(abs(u-.5)-.5,0.);
return (.5-texture(L,clamp(u,0.,1.)).r)*.2857+length(e*vec2(2.286,1.486));}
float shape(vec2 q){float b=sdb(vec2(q.x+q.y*.12,q.y+.03),vec2(.62,.19),.07);return mix(b,logo(q),M.w);}
void main(){float A=G.x,bt=G.y,mg=G.z,t=G.w*(1.-K.z);
vec2 p=vec2(v.x*A,v.y);vec2 hs=texture(H,v).rg;float hp=hs.r;
float dens=texture(D,vec2(clamp((p.x-mg)/(A-2.*mg),0.,1.),.5)).r;
float dl=texture(D,vec2(clamp((M.x-mg)/(A-2.*mg),0.,1.),.5)).r;
float ab=max(p.y-bt,0.),hz=exp(-ab*5.5);
vec3 c=vec3(.0045,.0038,.0034)+ramp(.45)*dens*hz*.12+ramp(.3)*exp(-ab*1.4)*.025+ramp(.5)*hp*.02;
c+=ramp(.4)*smoothstep(.35,.9,fbm(p*vec2(2.6,1.3)-vec2(0.,t*.07)))*exp(-ab*2.2)*(.3+dens)*.05;
float xc=(p.x-A*.5)/(A*.5),top=bt+.035*(1.-xc*xc)+(fbm(vec2(p.x*6.,2.))-.5)*.045,dy=top-p.y;
if(dy>-.03){float dep=clamp(dy/top,0.,1.);
vec2 cc=vec2(p.x,dy*1.5)*mix(44.,20.,sqrt(dep));cc+=(vec2(fbm(cc*.2),fbm(cc*.2+7.))-.5)*2.6;
vec3 f=vor(cc);float edge=f.y-f.x,lump=1.-f.x;
float pk=smoothstep(.28,.8,fbm(vec2(p.x*5.,dy*8.)+vec2(0.,t*.04)));
float fl=.75+.5*fbm(vec2(p.x*3.+f.z*4.,t*.22));
float hl=clamp((.12+dens*.95)*(.35+.65*dep)*(.4+.95*pk)*fl+hp*.8,0.,1.6);
float rim=exp(-edge*mix(26.,9.,min(hl,1.)));
vec3 bed=vec3(.0028,.0026,.0025)*(.3+lump*.9);
bed+=ramp(.16+.5*hl)*rim*hl*1.25+ramp(.14+.3*hl)*smoothstep(.55,1.,lump)*hl*hl*step(.8,f.z)*.9;
bed*=.2+.8*smoothstep(-.03,.05,dy);
c=mix(c,bed,smoothstep(-.03,.006,dy));}
vec2 w=vec2(n2(p*vec2(7.,4.)-vec2(0.,t*1.3)),n2(p*vec2(6.,3.)+vec2(3.,-t*1.1)))-.5;
vec2 q=(p+w*.008*hz*(.5+dens)-M.xy)/M.z;q.y*=1.+K.x*1.6;q.x*=1.-K.x*.4;
float d=shape(q),aa=fwidth(d)*.8+1e-4,T=K.y+hp*.85,m=smoothstep(aa,-aa,d),lo=smoothstep(.3,-.75,q.y);
vec3 am=vec3(1.,.197,.023)*K.w*(.8+.4*n2(vec2(q.x*4.,t*.5)));
if(m>0.){vec2 e=vec2(.004,0.);vec2 g=vec2(shape(q+e.xy)-d,shape(q+e.yx)-d)/.004;
float bev=smoothstep(0.,.045,-d);vec3 n=normalize(vec3(g*(1.-bev)*1.3,1.));
vec3 Lc=normalize(vec3(.1,-.85,.5)),Lt=normalize(vec3(-.45,.75,.55)),r=reflect(vec3(0.,0.,-1.),n);
float br=fbm(vec2(q.x*1.4,q.y*70.)),dc=max(dot(n,Lc),0.),dt=max(dot(n,Lt),0.);
vec3 cl=ramp(.62)*(.3+.7*dl);
vec3 lit=vec3(.028,.029,.031)*(.85+.3*br)*(.3+dc*cl*3.+dt*vec3(.3,.31,.33))+pow(max(dot(r,Lc),0.),12.)*cl*1.2+pow(max(dot(r,Lt),0.),24.)*vec3(.34,.35,.38)*(.6+.4*br);
float s=clamp(q.x*.32+.5+(n2(q*5.)-.5)*.5,0.,1.);vec3 tc=s<.5?mix(P[0],P[1],s*2.):mix(P[1],P[2],s*2.-1.);
float band=smoothstep(.03,.08,T)*(1.-smoothstep(.2,.3,T));
lit+=tc*band*(.06+.1*bev)+am*lo*((1.-bev)*(1.+max(-n.y,0.)*2.)+.2);
vec3 em=ramp(min(T,1.)*(.7+.22*bev)+.04)*min(pow(clamp(T,0.,1.3),1.7)*2.6,1.5)*(.45+.55*bev+.35*dt*(1.-bev));
c=mix(c,mix(lit,em,clamp(T*2.4,0.,1.))+em*.35,m);}
c+=ramp(T*.85)*min(pow(clamp(T,0.,1.3),2.),.45)*exp(-max(d,0.)*38.)*smoothstep(.14,.07,d)*(1.-m)*1.2;
c+=am*lo*exp(-max(d,0.)*40.)*(1.-m)*.6;
vec2 fd=p-F.xy;c+=R[5]*F.z*exp(-dot(fd,fd)*36.)*2.5;
vec2 vg=(v-.5)*vec2(1.,.85);c*=1.-.5*dot(vg,vg);
o=vec4(tone(c*1.15)+(h1(gl_FragCoord.xy+fract(t*7.)*97.)-.5)*(2./255.),1.);}`;const EMBER_V=HEAD+RAMP+`layout(location=0) in vec4 a;uniform vec4 G;uniform float s,hv;uniform sampler2D H;out vec3 c;out float r;
void main(){vec2 u=vec2(a.x/G.x,a.y);float hp=texture(H,u).r,hov=float(gl_VertexID)==hv?1.:0.;
float fl=1.+.16*sin(G.w*(1.1+a.w*1.7)+a.w*50.)*sin(G.w*.63+a.w*13.);
c=ramp(clamp(.4+.52*a.z+hp*.35,0.,1.))*(.8+1.6*a.z*a.z+hp*1.5+hov*1.2)*fl;r=hov;
gl_PointSize=(2.+3.2*a.z+hp*2.+hov*2.5)*s*3.5;gl_Position=vec4(u*2.-1.,0.,1.);}`;const EMBER_F=HEAD+RAMP+`in vec3 c;in float r;out vec4 o;
void main(){float l=length(gl_PointCoord*2.-1.)*3.5;
float e=max(0.,1.-l/3.5);vec3 col=c*(smoothstep(1.,.5,l)*1.6+exp(-l*l*.45)*e*e*.5)+r*smoothstep(.3,0.,abs(l-2.3))*vec3(1.,.75,.45);
o=vec4(tone(col),1.);}`;const SPARK_V=HEAD+`layout(location=0) in vec4 a;uniform vec4 G;uniform float ps;out float l,k;
void main(){l=a.z;k=a.w;gl_PointSize=ps;gl_Position=vec4(a.x/G.x*2.-1.,a.y*2.-1.,0.,1.);}`;const SPARK_F=HEAD+RAMP+`in float l,k;out vec4 o;
void main(){float L=clamp(l,0.,1.);o=vec4(tone(ramp(.45+.55*L)*(1.1+3.2*L)*(1.-k*.93)),1.);}`;
return{TRI,HEAT,MAIN,EMBER_V,EMBER_F,SPARK_V,SPARK_F}})();
const __sparksjs=(()=>{function createSparks(max=384){const s=new Float32Array(max*6);const verts=new Float32Array(max*8);let n=0;let cap=max;return{get count(){return n;},set cap(v){cap=Math.min(max,v);n=Math.min(n,cap);},emit(x,y,count,vx=0,vy=0.6,spread=1,rnd=Math.random){for(let k=0;k<count&&n<cap;k++,n++){const a=Math.PI*0.5+(rnd()-0.5)*Math.PI*1.25*spread;const sp=(0.25+rnd()*rnd()*1.15)*(0.6+spread*0.5);const o=n*6;s[o]=x+(rnd()-0.5)*0.01;s[o+1]=y+(rnd()-0.5)*0.01;s[o+2]=vx+Math.cos(a)*sp;s[o+3]=vy*0.4+Math.sin(a)*sp;s[o+4]=1;s[o+5]=0.55+rnd()*1.1;}},step(dt,floor){const drag=Math.pow(0.985,dt*60);let w=0;for(let i=0;i<n;i++){const o=i*6;s[o+4]-=dt*s[o+5];if(s[o+4]<=0)continue;s[o+3]-=1.55*dt;s[o+2]*=drag;s[o+3]*=drag;s[o]+=s[o+2]*dt;s[o+1]+=s[o+3]*dt;if(s[o+1]<floor&&s[o+3]<0){s[o+3]*=-0.3;s[o+2]*=0.55;s[o+4]-=0.3;}
if(w!==i)s.copyWithin(w*6,o,o+6);w++;}
n=w;for(let i=0;i<n;i++){const o=i*6;const v=i*8;const k=0.022;verts[v]=s[o];verts[v+1]=s[o+1];verts[v+2]=s[o+4];verts[v+3]=0;verts[v+4]=s[o]-s[o+2]*k;verts[v+5]=s[o+1]-s[o+3]*k;verts[v+6]=s[o+4];verts[v+7]=1;}
return verts.subarray(0,n*8);},clear(){n=0;},};}
return{createSparks}})();
const{program,texture,framebuffer,loadImage}=__gljs;const S=__shadersjs;const{createSparks}=__sparksjs;const lin=(hex)=>rgb01(hex).map((v)=>v**2.2);const RAMP=new Float32Array(HEAT.flatMap(lin));const TEMP=new Float32Array(TEMPER.flatMap(lin));const SDF_URL=new URL("../../assets/img/logo-sdf.png",import.meta.url).href;const STRIKE_AT=[0.4,0.9,1.4];const FORGE_TO=[0.45,0.8,1];const COOL=3.2;const IDLE_FPS=24;const backOut=(x)=>1+2.2*(x-1)**3+1.2*(x-1)**2;let sdfImage=null;const restHeat=(embers)=>(embers.length?0.12*Math.min(1,embers.filter((e)=>e.days<=30).length/embers.length/0.1):0);export function createForge(canvas,{repos,asOf,dpr=1,maxSparks=384}){const gl=canvas.getContext("webgl2",{antialias:false,alpha:false,depth:false,stencil:false,powerPreference:"low-power"});if(!gl)return null;const embers=buildEmbers(repos,asOf);const rest=restHeat(embers);const sparks=createSparks(maxSparks);const st={t:0,dt:0,intro:0,introDone:false,forge:0,from:0,to:0,last:-9,temp:1,squash:0,flash:[0,0,0],splats:[],hover:-1,freeze:0,div:4,fired:0};const R8=()=>({internal:gl.R8,format:gl.RED,type:gl.UNSIGNED_BYTE});let r=null;let W=1,H=1,A=1,lay=layout(1),format="RGBA8";function heatFormat(){if(!(gl.getExtension("EXT_color_buffer_float")||gl.getExtension("EXT_color_buffer_half_float")))return"RGBA8";const t=texture(gl,{w:4,h:4,internal:gl.RG16F,format:gl.RG,type:gl.HALF_FLOAT});const f=framebuffer(gl,t);gl.deleteTexture(t);if(f)gl.deleteFramebuffer(f);return f?"RG16F":"RGBA8";}
function heatTargets(){for(const x of r.heat??[])gl.deleteTexture(x.t),gl.deleteFramebuffer(x.f);r.hw=Math.max(8,Math.round(W/st.div));r.hh=Math.max(8,Math.round(H/st.div));const spec=format==="RG16F"?{internal:gl.RG16F,format:gl.RG,type:gl.HALF_FLOAT}:{internal:gl.RGBA8,format:gl.RGBA,type:gl.UNSIGNED_BYTE};r.heat=[0,1].map(()=>{const t=texture(gl,{w:r.hw,h:r.hh,...spec});const f=framebuffer(gl,t);gl.bindFramebuffer(gl.FRAMEBUFFER,f);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);return{t,f};});gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
function init(){format=heatFormat();r={heatP:program(gl,S.TRI,S.HEAT),main:program(gl,S.TRI,S.MAIN),ember:program(gl,S.EMBER_V,S.EMBER_F),spark:program(gl,S.SPARK_V,S.SPARK_F)};[r.vao,r.ev,r.sv,r.hv]=[0,0,0,0].map(()=>gl.createVertexArray());[r.eb,r.sb]=[gl.createBuffer(),gl.createBuffer()];r.dens=texture(gl,{w:128,h:1,...R8(),data:densityRow(embers)});r.sdf=sdfImage?texture(gl,{image:sdfImage,...R8()}):texture(gl,{w:1,h:1,...R8(),data:new Uint8Array(1)});const attrib=(vao,buf,stride,bytes)=>{gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,buf);if(bytes)gl.bufferData(gl.ARRAY_BUFFER,bytes,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,stride,0);};attrib(r.ev,r.eb,16,0);attrib(r.sv,r.sb,16,maxSparks*32);attrib(r.hv,r.sb,32,0);gl.bindVertexArray(null);r.ping=0;heatTargets();placeEmbers();}
function placeEmbers(){if(!r||!embers.length)return;gl.bindBuffer(gl.ARRAY_BUFFER,r.eb);gl.bufferData(gl.ARRAY_BUFFER,emberBuffer(embers,lay),gl.STATIC_DRAW);}
function setSize(cssW,cssH){W=Math.max(2,Math.round(cssW*dpr));H=Math.max(2,Math.round(cssH*dpr));if(canvas.width!==W||canvas.height!==H)(canvas.width=W),(canvas.height=H);A=W/H;lay=layout(A);if(r)heatTargets(),placeEmbers();}
function setSdf(img){sdfImage=img;if(r)gl.deleteTexture(r.sdf),(r.sdf=texture(gl,{image:img,...R8()}));}
function strike(x,y,power=1,burst=80){const now=performance.now()/1000;if(now-st.last<0.5)return false;st.last=now;const L=lay.logo;st.squash=Math.abs(x-L.cx)<L.hw*1.05&&Math.abs(y-L.cy)<L.hw*0.66?0.07*power:0;st.flash=[x,y,0.9*power];st.splats.push([x/A,y,0.055,2.4*power]);sparks.emit(x,y,burst,0,0.9,1.1);return true;}
function stepIntro(dt,onStrike,onCooled){if(st.introDone)return;st.intro+=dt;const L=lay.logo;while(st.fired<3&&st.intro>=STRIKE_AT[st.fired]){st.from=st.forge;st.to=FORGE_TO[st.fired];st.last=-9;strike(L.cx+(Math.random()-0.5)*L.hw*0.8,L.cy+L.hw*0.3,0.8,60+Math.round(Math.random()*40));onStrike?.(++st.fired);}
if(st.fired)st.forge=st.from+(st.to-st.from)*backOut(Math.min(1,(st.intro-STRIKE_AT[st.fired-1])/0.22));const after=st.intro-STRIKE_AT[2];st.temp=after<0?1-st.fired*0.04:0.88*Math.exp(-after/0.8);if(after>COOL)cool(),onCooled?.();}
function cool(){Object.assign(st,{introDone:true,fired:3,forge:1,temp:0});}
function step(dt,p){st.t+=dt;st.dt=dt;st.squash*=0.0005**dt;if(p?.amt>0)st.splats.push([p.x/A,p.y,0.05,p.amt]);return sparks.step(dt,lay.bedTop-0.015);}
const bind=(i,t)=>(gl.activeTexture(gl.TEXTURE0+i),gl.bindTexture(gl.TEXTURE_2D,t));function draw(sv=new Float32Array(0)){if(!r||gl.isContextLost())return;const src=r.heat[r.ping];const dst=r.heat[1-r.ping];const L=lay.logo;gl.disable(gl.BLEND);gl.bindFramebuffer(gl.FRAMEBUFFER,dst.f);gl.viewport(0,0,r.hw,r.hh);let u=r.heatP.u;gl.useProgram(r.heatP.p);bind(0,src.t);gl.uniform1i(u.T,0);gl.uniform2f(u.px,1/r.hw,1/r.hh);gl.uniform3f(u.k,0.35**st.dt,0.8**st.dt,format==="RGBA8"?1.2/255:0.0004);const sp=new Float32Array(16);st.splats.splice(0).slice(0,4).forEach((s,i)=>sp.set(s,i*4));gl.uniform4fv(u.S,sp);gl.uniform1f(u.A,A);gl.bindVertexArray(r.vao);gl.drawArrays(gl.TRIANGLES,0,3);r.ping=1-r.ping;gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,W,H);u=r.main.u;gl.useProgram(r.main.p);[dst.t,r.dens,r.sdf].forEach((t,i)=>bind(i,t));gl.uniform1i(u.H,0);gl.uniform1i(u.D,1);gl.uniform1i(u.L,2);gl.uniform3fv(u.R,RAMP);gl.uniform3fv(u.P,TEMP);gl.uniform4f(u.G,A,lay.bedTop,lay.margin,st.t);gl.uniform4f(u.M,L.cx,L.cy,L.hw,sdfImage?st.forge:0);gl.uniform4f(u.K,st.squash,st.temp,st.freeze,rest);gl.uniform4f(u.F,...st.flash,0);st.flash[2]=0;gl.drawArrays(gl.TRIANGLES,0,3);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);if(embers.length){u=r.ember.u;gl.useProgram(r.ember.p);bind(0,dst.t);gl.uniform1i(u.H,0);gl.uniform3fv(u.R,RAMP);gl.uniform4f(u.G,A,lay.bedTop,lay.margin,st.t);gl.uniform1f(u.s,Math.max(H/570,dpr*0.85));gl.uniform1f(u.hv,st.hover);gl.bindVertexArray(r.ev);gl.drawArrays(gl.POINTS,0,embers.length);}
const n=sv.length/4;if(n){u=r.spark.u;gl.useProgram(r.spark.p);gl.uniform3fv(u.R,RAMP);gl.uniform4f(u.G,A,lay.bedTop,lay.margin,st.t);gl.bindBuffer(gl.ARRAY_BUFFER,r.sb);gl.bufferSubData(gl.ARRAY_BUFFER,0,sv);gl.uniform1f(u.ps,1.6*dpr);gl.bindVertexArray(r.sv);gl.drawArrays(gl.LINES,0,n);gl.uniform1f(u.ps,2.2*dpr);gl.bindVertexArray(r.hv);gl.drawArrays(gl.POINTS,0,n/2);}
gl.bindVertexArray(null);}
return{gl,st,sparks,embers,init,setSize,setSdf,strike,stepIntro,cool,step,draw,get lay(){return lay;},get A(){return A;},get format(){return format;},lower(level){if(level===1)(st.div=8),(sparks.cap=192),r&&heatTargets();else st.freeze=1;},};}
export function start(stage,opts={}){const mobile=Boolean(opts.mobile);const dpr=mobile?1:Math.min(devicePixelRatio||1,1.5);const canvas=document.createElement("canvas");canvas.className="esse-canvas";canvas.setAttribute("aria-hidden","true");let forge;try{forge=createForge(canvas,{repos:opts.repos,asOf:opts.asOf,dpr,maxSparks:mobile?160:384});if(!forge)return null;forge.init();}catch(error){console.warn("[esse] WebGL2:",error);return null;}
stage.append(canvas);let frames=0,raf=0,idle=0,woke=false,last=0,strikes=0,lostTimer=0;let visible=true,calm=false,lost=false,dead=false,live=false,ready=false;let gov=[0,0,0];const P={x:0,y:0,vx:0,amt:0,speed:0,pt:0,inside:false};if(opts.skipIntro)forge.cool();const on=(t,type,fn)=>t.addEventListener(type,fn);const fire=(n)=>{document.dispatchEvent(new CustomEvent("forge:strike",{detail:{n}}));if(!mobile&&!calm)canvas.animate([{translate:"0 0"},{translate:"-3px 2px"},{translate:"3px -1px"},{translate:"-1px 1px"},{translate:"0 0"}],120);};const cooled=()=>(document.dispatchEvent(new CustomEvent("esse:cooled")),opts.onCooled?.());const running=()=>ready&&visible&&!document.hidden&&!calm&&!lost&&!dead;const quiet=()=>forge.st.introDone&&!P.inside&&!forge.sparks.count&&performance.now()/1000-forge.st.last>3;function size(){const b=stage.getBoundingClientRect();if(b.width<2||b.height<2)return;forge.setSize(b.width,b.height);if(!running())paintStatic();}
function reveal(){if(live)return;live=true;canvas.classList.add("is-live");opts.onLive?.();}
function paintStatic(){if(!ready||lost||dead)return;if(calm)forge.cool(),forge.sparks.clear();forge.draw(forge.step(0,null));reveal();}
function frame(now){raf=0;if(!running())return;const dt=last?Math.min(0.05,(now-last)/1000):1/60;last=now;if(!woke){gov[0]+=dt;if(++gov[1]===30){if(gov[0]/30>0.022&&gov[2]<2)forge.lower(++gov[2]);gov[0]=gov[1]=0;}}
forge.stepIntro(dt,fire,cooled);P.amt=0;if(P.inside&&P.speed>0.05){P.amt=Math.min(0.35,P.speed*0.12);const n=Math.min(20,Math.floor(P.speed*3*Math.random()));if(n)forge.sparks.emit(P.x,P.y,n,P.vx*0.3,0.5,0.7);P.speed*=0.5;}
forge.draw(forge.step(dt,P));frames++;reveal();woke=false;if(quiet())idle=setTimeout(()=>((idle=0),(woke=true),(raf=requestAnimationFrame(frame))),1000/IDLE_FPS-4);else raf=requestAnimationFrame(frame);}
const stop=()=>(raf&&cancelAnimationFrame(raf),clearTimeout(idle),(raf=idle=0));const kick=()=>{if(!running()||raf)return;if(!idle)last=0;clearTimeout(idle);idle=0;raf=requestAnimationFrame(frame);};const toPanel=(e)=>{const b=canvas.getBoundingClientRect();return[((e.clientX-b.left)/b.width)*forge.A,1-(e.clientY-b.top)/b.height,b];};function hover(i){if(i===forge.st.hover)return;forge.st.hover=i;opts.onHover?.(i>=0?forge.embers[i]:null);if(!running())paintStatic();}
const fine=matchMedia("(hover: hover) and (pointer: fine)");on(canvas,"pointermove",(e)=>{if(e.pointerType!=="mouse"&&e.pointerType!=="pen")return;const[x,y,b]=toPanel(e);const now=performance.now();const dtp=Math.max(0.008,(now-P.pt)/1000);if(P.inside)(P.speed=Math.max(P.speed,Math.hypot(x-P.x,y-P.y)/dtp)),(P.vx=(x-P.x)/dtp);Object.assign(P,{x,y,pt:now,inside:!mobile&&fine.matches});if(P.inside)kick();const L=forge.lay;let best=-1;let bd=(14/b.height)**2;forge.embers.forEach((em,i)=>{const d=(emberX(em.t,L)-x)**2+(emberY(em.j,L)-y)**2;if(d<bd)(bd=d),(best=i);});hover(best);});on(canvas,"pointerleave",()=>((P.inside=false),hover(-1)));on(canvas,"pointerdown",(e)=>{if(e.button>0||calm||!ready)return;const[x,y]=toPanel(e);doStrike(x,y);});function doStrike(x,y){if(!forge.strike(x,y))return false;fire((strikes++%3)+1);kick();return true;}
const io=new IntersectionObserver(([e])=>((visible=e.isIntersecting&&e.intersectionRatio>=0.05),visible?kick():stop()),{threshold:[0,0.05,0.2]});io.observe(stage);const ro=new ResizeObserver(size);ro.observe(stage);const onVis=()=>(document.hidden?stop():kick());on(document,"visibilitychange",onVis);on(canvas,"webglcontextlost",(e)=>{e.preventDefault();lost=true;live=false;stop();canvas.classList.remove("is-live");opts.onLost?.();lostTimer=setTimeout(()=>destroy(true),4000);});on(canvas,"webglcontextrestored",()=>{clearTimeout(lostTimer);if(dead)return;try{forge.init();lost=false;size();opts.onRestored?.();running()?kick():paintStatic();}catch{destroy(true);}});loadImage(SDF_URL).then((img)=>forge.setSdf(img)).catch(()=>forge.cool()).finally(()=>{ready=true;size();running()?kick():paintStatic();});function destroy(fromLoss=false){if(dead)return;dead=true;stop();io.disconnect();ro.disconnect();clearTimeout(lostTimer);document.removeEventListener("visibilitychange",onVis);canvas.remove();if(fromLoss)opts.onDead?.();}
return{canvas,destroy,get frames(){return frames;},get format(){return forge.format;},strike(){const L=forge.lay.logo;return!calm&&ready&&doStrike(L.cx+(Math.random()-0.5)*L.hw*0.6,L.cy+L.hw*0.25);},setCalm(c){calm=Boolean(c);calm?(stop(),paintStatic()):kick();},forge,loseContext:()=>forge.gl.getExtension("WEBGL_lose_context"),};}
